---
title: Just-in-Time Access
date-modified: 09/23/2025
lightbox: true
---


*Just-in-Time Access* (JIT) er en applikasjon der [data-admins](../hva-er-dapla-team.qmd#data-admins) kan gi seg selv midlertidig tilgang knyttet til [kildedata](../datatilstander.qmd#kildedata). Hovedsakelig benyttes dette for å aktivere tilgang til Transfer Service i kildeprosjektet, og for å aktivere tilgang til å liste ut filer i kildeprosjektet.

På Dapla benyttes for dette for å unngå at data-admins har permanent tilgang til sensitive data, siden all kildedata er definert som sensitiv informasjon. *data-admins* må bruke JIT-applikasjonen for å gi seg selv korte, begrunnede tilganger til kildedata ved behov. Den som er ansvarlig for teamet kan monitere i hvilken grad teamets data-admins benytter seg av denne muligheten.

## Hvordan bruke JIT

For å bruke JIT må du være [data-admin](../hva-er-dapla-team.qmd#data-admins) for teamet som eier kildedataene du ønsker tilgang til. Du aktiverer tilganger i JIT-appen ved gjøre følgende:

1. Gå inn på nettsiden <https://jitaccess.dapla.ssb.no/>^[Hvis du jobber fra hjemmekontor så må du være på VPN for å få tilgang til JIT-appen.]
1. Oppgi [Prosjekt-id](../../faq.qmd#hvordan-finner-jeg-et-google-prosjekt-sin-prosjekt-id) for prosjektet der kildedataene du ønsker tilgang til er lagret. 
2. Huk av hvilke tilgangsroller du ønsker aktivert. Se beskrivelse av roller i @tbl-jit-roles.
3. Velg hvor lenge tilgangen du ønsker at tilgangen skal vare. Den kan maksimalt vare i 8 timer. 
4. Oppgi en begrunnelse for at aktiverer tilgangen. 
5. Til slutt trykker du på **Request access**.

Tilgangen vil deretter være aktiv ila. noen minutter. 

::: {.callout-note}
# Hvordan bør begrunnelsen skrives?
Prøv å gjør begrunnelsen forståelig for andre enn deg selv på det tidspunktet. Den som er ansvarlig for teamet skal kunne forstå begrunnelsen når de ser på loggene. I tillegg vil sentralt i SSB monitere i hvilken grad Dapla-teamene benytter seg av tilgangene.  
:::

| Roller                | Hva?                                                   |
| --------------------- | ------------------------------------------------------ |
| ssb.buckets.list      | Liste ut bøttene i kildeprosjektet.                    |
| storagetransfer.admin | Sette opp jobb med Transfer Service i kildeprosjektet. |
| ssb.bucket.write      | Lese og skrive til kildebøtta.                         |
: De mest relevante tilgangene som kan aktiveres i JIT-applikasjonen {#tbl-jit-roles}

Skal du sette opp en Transfer Service overføring med kildedata så må du aktivere **ssb.bucket.write** og **storagetransfer.admin**.