# Administrasjon av team

I dette kapitlet viser vi hvordan du kan opprette et nytt team eller gjøre endringer i et eksisterende team. Typiske endringer er å: 

- Legge til, fjerne eller endre medlemmer i et team
- Liste ut medlemmer og tilgangsgrupper i et team

## Opprette Dapla-team

For å opprette et Dapla-team så må en seksjonsleder gå inn i Teamoversikten i [Dapla Ctrl](https://dapla-ctrl.intern.ssb.no/) og trykke på ikonet **Opprett team**. Her blir man bedt om å fylle inn relevant informasjon. 

::: {.callout-note}
Les mer om [Dapla Ctrl her](./dapla-ctrl.html). 
:::

## Legge til eller fjerne medlemmer i et team

For å legge til, fjerne eller endre medlemmer i et team må kan gjøres av medlemmer i [managers](./hva-er-dapla-team.html#managers)-gruppen i teamet. Dette gjøres i [Dapla Ctrl](./dapla-ctrl.html). Les mer om [hvordan dette gjøres her](./dapla-ctrl.html#legge-til-medlemmer).

::: {.callout-warning}
## Managers i *semi*- eller *self-managed* team
Managers i semi- eller self-managed teams kan ikke legge til, fjerne eller endre medlemmer fra Dapla Ctrl enda. Disse må foreløpig kontakte Kundeservice for å gjøre endringer. 
:::

## Se medlemmer og roller i et team

[Dapla Ctrl](https://ctrl.dapla.ssb.no/) lar alle i SSB se hvilke team som finnes, hvem som er medlemmer og hvilke tilgangsgrupper de ligger i. Man kan også få oversikt over hvilke data alle team deler. [Les mer her](./dapla-ctrl.qmd#teammedlemmer). 

