---
title: Hente data fra bakke
date-modified: 11/14/2025
lightbox: true
---

Denne kapitlet beskriver hvordan man kan bruke [dapla-suv-tools pakken](./altinn-dapla-suv-tools.html) for å hente utvalg, enhetsinformasjon, delregister og vareliste fra SFU i Dapla-miljøet. I tillegg finnes det funksjonalitet for å hente prefill fra ISEE.

Det finnes fortsatt avhengigheter til bakkesystemene for å kunne kjøre et fullstendig produksjonsløp på Dapla. SU-V har laget integrasjoner mellom bakke- og skyløsninger der det er behov for dette. Administrasjon av utvalg og enheter skjer fortsatt fra SFU på bakke.

## Forberedelser

For å kunne hente enhetsinformasjon fra SFU må brukeren din ha tilgang til delregisteret i riktig miljø (DB1T/DB1P). Ta kontakt med Kundeservice dersom du opplever problemer med tilganger. 

I tillegg må `dapla-suv-tools` være installert i en tjeneste på [Dapla Lab](./dapla-lab.qmd):

```{.bash filename="terminal"}
poetry add dapla-suv-tools
```

## Funksjonalitet

Under finner du eksempler på funksjonalitet som tilbys i `dapla-suv-tools` for å jobbe med SFU fra Dapla Lab. 

### Hente utvalg fra SFU

For å hente utvalg fra SFU, bruk metoden `get_utvalg_from_sfu` i `SuvClient`. Sørg for at du oppgir riktig delregisternummer og RA-nummer for utvalget.

```{.python filename="notebook"}
client = SuvClient()

response = client.get_utvalg_from_sfu(
    delreg_nr=49430224,
    ra_nummer='RA-0666A3'
)

print(json.dumps(response, indent=4))
```
::: {.callout-tip collapse="true"}
## Frivillige parametere

Disse parameterne kan brukes for å filtrere resultatet ytterligere:

| Parameter | Type | Beskrivelse |
|------------|------|-------------|
| `pulje` | int | Hent spesifikk pulje |
| `status` | string | Hent spesifikk status. Mulige verdier er "besvart", "ikke-besvart", "alle" |
| `max_results` | int | Maks antall resultater som returneres |
| `pagination_info` | object | Pagineringsinformasjon |

Eksempel:
```python
response = client.get_utvalg_from_sfu(
    delreg_nr=49430224,
    ra_nummer='RA-0666A3',
    pulje='2',
    status='ikke-besvart',
    max_results=200,
    pagination_info=p_info
)

print(json.dumps(response, indent=4))
```
:::

### Hente enhetsinformasjon fra SFU

For å hente enhetsinformajon fra SFU, bruk metoden `get_enhet_from_sfu` i `SuvClient`. Sørg for at du oppgir riktig delregisternummer og organisajonsnummer.

```{.python filename="notebook"}
client = SuvClient()

response = client.get_enhet_from_sfu(
    delreg_nr=49430224,
    orgnr='123456789' 
)

print(json.dumps(response, indent=4))
```
::: {.callout-caution collapse="true"}
## Vis output

```json
{
    "delreg_nr": 49430224,
    "ident_nr": "A3TF0019",
    "orgnr": "123456789",
    "enhets_type": "FRTK",
    "foretak": "A3TF0019",
    "orgnr_foretak": "123456789",
    "flv": "0",
    "navn1": "MITT REGNSKAP",
    "navn2": null,
    "navn3": null,
    "f_adresse1": "Testvegen 19",
    "f_adresse2": null,
    "f_adresse3": null,
    "f_postnr": "0019",
    "f_poststed": "OSLO",
    "skj_enh_ident_nr": "ATB1247288",
    "skj_enh_orgnr": "987654321",
    "skj_enh_enhets_type": "BEDR",
    "skj_enh_navn": "MITT REGNSKAP",
    "skj_enh_adresse": "Regnskpvegen 250",
    "skj_enh_postnr": "1111",
    "skj_enh_poststed": "ARENDAL",
    "skj_enh_avdeling": "AVD ARENDAL",
    "maalform": null,
    "kontaktperson": "OLA NORDMANN",
    "kont_telefon": "12121212",
    "kont_mobiltlf": null,
    "kont_epost": null,
    "h_var1_n": null,
    "h_var2_n": null,
    "h_var3_n": null,
    "h_var1_a": null,
    "h_var2_a": null,
    "h_var3_a": null,
    "utvalgsstatus": null,
    "pulje_nr": 2,
    "vedtak_tvmulkt": "N",
    "sendt_si": "N",
    "status": null,
    "org_form": null,
    "sn07_1": "17.120",
    "str_kode": null,
    "viktig_enhet": null,
    "kommentar_int": null,
    "kommentar_ekst": null,
    "test_pulje": null,
    "skjema_type": "RA-0666A3",
    "dato_innkvittering": null,
    "kvitt_type": null,
    "kvitt_format": null,
    "kvitt_undertype": null,
    "kvitt_nivaa": null
}
```

:::

### Hente delregister fra SFU

For å hente delregister fra SFU, bruk metoden `get_delreg_from_sfu` i `SuvClient`. Sørg for at du oppgir riktig delregisternummer. Metoden vil returnere alle enheter i angitt delregister.

```{.python filename="notebook"}
client = SuvClient()

response = client.get_delreg_from_sfu(
    delreg_nr=49430224    
)

print(json.dumps(response, indent=4))
```

::: {.callout-tip collapse="true"}
## Frivillige parametere

Disse parameterne kan brukes for å filtrere resultatet ytterligere:

| Parameter | Type | Beskrivelse |
|------------|------|-------------|
| `enhets_type` | str | Hent spesifikk enhetstype |
| `max_results` | int | Maks antall resultater som returneres |
| `pagination_info` | object | Pagineringsinformasjon |

Eksempel:
```python
response = client.get_delreg_from_sfu(
    delreg_nr=49430224,
    enhets_type='FRTK',
    max_results=200,
    pagination_info=p_info
)

print(json.dumps(response, indent=4))
```
:::

### Hente vareliste fra SFU

For å hente vareliste fra SFU, bruk metoden `get_vareliste` i `SuvClient`. Sørg for at du oppgir riktig delregisternummer og RA-nummer.

```{.python filename="notebook"}
client = SuvClient()

response = client.get_vareliste(
    delreg_nr=769523,
    ra_nummer="RA-0830A3" 
)

print(json.dumps(response, indent=4))
```

::: {.callout-caution collapse="true"}
## Vis output

```json
{
    "delreg_nr": 769523,
    "ident_nr": "A3TF0001",
    "enhets_type": "FRTK",
    "skjema_type": "RA-0830A3",
    "katalog_id": 81,
    "felt": "ORGNR",
    "rad_nr": 1,
    "felt_verdi": "900000001",
    "aktiv": "Y",
    "endret_av": "ABC",
    "endret_dato": null
}
```

:::

::: {.callout-tip collapse="true"}
## Frivillige parametere

Disse parameterne kan brukes for å filtrere resultatet ytterligere:

| Parameter | Type | Beskrivelse |
|------------|------|-------------|
| `ident_nr` | str | Hent spesifikk enhet |
| `enhets_type` | str | Hent spesifikk enhetstype |
| `katalog_id` | str | Hent bare spesifikk katalog |
| `aktiv` | str | Hent spesifikk aktiv status |
| `felt_ids` | list[str] | Hent bare spesifikke felt |
| `max_results` | int | Maks antall resultater som returneres |
| `pagination_info` | object | Pagineringsinformasjon |

Eksempel:
```python
response = client.get_vareliste(
    delreg_nr=769523,
    ra_nummer="RA-0830A3",
    ident_nr="A3TF0001",
    enhets_type="FRTK",
    katalog_id=81,
    aktiv='Y',
    felt_ids=["ORGNR", "NAVN"],
    max_results=100,
    pagination_info=p_info
)

print(json.dumps(response, indent=4))
```
:::

### Hente prefill fra ISEE

For å hente prefill fra ISEE, bruk metoden `get_prefill_isee` i `SuvClient`. Sørg for at du oppgir riktig delregisternummer og RA-nummer.

```{.python filename="notebook"}
client = SuvClient()

response = client.get_prefill_isee(
    delreg_nr=190125,
    ra_nummer="RA-0484A3" 
)

print(json.dumps(response, indent=4))
```

::: {.callout-caution collapse="true"}
## Vis output

```json
{
    "delreg_nr": 190125,
    "enhets_id": "ATB1149185",
    "skjema": "RA-0484A3",
    "lopenr": 3,
    "felt_id": "BESKRIVELSE",
    "felt_verdi": "Corona",
    "kilde": "DYNAREV",
    "endret_dato": "2025-11-07T09:35:42.000",
    "endret_av": "SUV_ORDS",
    "enhets_type": "BEDR",
    "rad_nr": 1,
    "for_kilde": "DEFAULT",
    "nokkel_verdier": null
}
```

:::

::: {.callout-tip collapse="true"}
## Frivillige parametere

Disse parameterne kan brukes for å filtrere resultatet ytterligere:

| Parameter | Type | Beskrivelse |
|------------|------|-------------|
| `ident_nr` | str | Hent spesifikk enhet |
| `enhets_type` | str | Hent spesifikk enhetstype |
| `felt_ids` | list[str] | Hent bare spesifikke felt |
| `max_results` | int | Maks antall resultater som returneres |
| `pagination_info` | object | Pagineringsinformasjon |

Eksempel:
```python
response = client.get_prefill_isee(
    delreg_nr=190125,
    ra_nummer="RA-0484A3",
    ident_nr="ATB1149212",
    enhets_type="BEDR",
    felt_ids=["VARENAVN", "VARENR"],
    max_results=200,
    pagination_info=p_info
)

print(json.dumps(response, indent=4))
```
:::

