---
title: dapla-toolbelt-datafangst
date-modified: "07/02/2026"
lightbox: true
---

[dapla-toolbelt-datafangst](https://pypi.org/project/dapla-toolbelt-datafangst/) er en Python-pakke for å jobbe med datafangst-relaterte systemer på Dapla. Pakken gir brukeren et Python-grensesnitt for å jobbe mot [KuDoc](./kudoc.qmd) via [kudoc-client](./kudoc-client.qmd)-delen av pakken.

## Forberedelser

dapla-toolbelt-datafangst kan installeres i tjenester på Dapla Lab. Siden det er en Python-pakke så må den installeres i en tjeneste der Python er installert. Deretter gjør du følgende:

1.  Åpne en tjeneste på [Dapla Lab](https://lab.dapla.ssb.no/) med Python installert.
2.  Installer pakken i et [ssb-project](./ssb-project.qmd) på følgende måte:

``` {.bash filename="Terminal"}
poetry add dapla-toolbelt-datafangst
```

For å bruke pakken trenger du også:

- Python 3.12 eller høyere
- En gyldig Dapla-brukerkonto (for autentisering)
- Miljøvariabelen `DAPLA_ENVIRONMENT` satt når du kjører på Dapla-plattformen

Etter det er du klar for å bruke funksjonaliteten i *dapla-toolbelt-datafangst* i en notebook. Se [kudoc-client](./kudoc-client.qmd) for hvordan du bruker pakken til å jobbe med KuDoc.
