---
title: Etablering og endring av datainnsamlinger
date-modified: 09/01/2026
lightbox: true
---

Alle forslag om nye datainnsamlinger, eller vesentlige endringer i eksisterende datainnsamlinger, skal behandles i samarbeid med avdeling 800 Metodeutvikling og datainnsamling. Dette gjelder både innsamlinger basert på skjemarapportering, spørreundersøkelser, API-løsninger og andre metoder for innhenting av data. Formålet er å sikre at databehovet er tilstrekkelig vurdert, at eksisterende datakilder er undersøkt, og at innsamlingen planlegges og gjennomføres på en effektiv og koordinert måte. Før beslutning om bruk av opplysningsplikt skal det gjennomføres lovpålagt kost-/nyttevurdering.

Bestilling av ny eller endring av eksisterende datainnsamling gjøres i PureService.

## Krav til dokumentasjon i KuDoc

Før det søkes om etablering av en ny datainnsamling eller endringer i en eksisterende innsamling, skal relevante opplysninger registreres i [KuDoc](./kudoc.qmd). Registreringen skal gi en beskrivelse av formålet med innsamlingen, hvilke kilder som dataene skal innhentes fra, type enheter, innsamlingsmetode, frekvens, kontaktinformasjon og eventuelle tilhørende dokumenter, inkludert utvalgsplan der dette er aktuelt. KuDoc fungerer som SSBs felles kilde for dokumentasjon av datainnsamlinger og gir beslutningstakere og støttefunksjoner et felles grunnlag for vurdering og videre behandling av saken. En søknad om etablering eller endring av datainnsamling kan derfor ikke behandles før nødvendig dokumentasjon er registrert og oppdatert i KuDoc.