# Datadoc

::: {.callout-warning}
NB! Advarsel - Ustabilitet i Dapla Beta!
:::

Statistikkmetadata er strukturert informasjon om statistikk. Dette omfatter informasjon som brukes for å produsere, formidle, forstå, finne 
eller gjenbruke statistikk. For å kunne gjenfinne data i SSB er man helt avhengig av at det finnes et enhetlig system for metadata knyttet til dataene. 

## Hva er Datadoc

Datadoc er en tjeneste som skal forenkle arbeidet med å dokumentere datasett og variabelforekomster.
Felt og datatyper er definert som JSON schema i [ssb-datadoc-model](https://github.com/statisticsnorway/ssb-datadoc-model).
DataDoc har et grensesnitt basert på [SSB-design-system](https://design.ssb.no/) bygget med [ssb-dash-components](https://pypi.org/project/ssb-dash-components/).

Foreløpig støtter løsningen følgende filformater:

1. parquet
2. sas7bdat


## Innlogging

DataDoc er en tjeneste som er tilgjengelig for alle ssb ansatte på [Dapla](https://lab.dapla-test.ssb.no/).

For å logge inn gjør du følgende:

1.Åpne [Dapla](https://lab.dapla-test.ssb.no/).
2.Logg deg inn med din SSB-bruker





## Hvordan dokumentere et datasett

### Datasett/Navnestandarden...

### Obligatorisk/anbefalt/maskingenerert...

## Lagre metadata

## Oppdatere eksisterende metadata