---
title: "Hurtigstart: eksempelkode"
--- 

### Hvordan tar jeg editeringsrammeverket i bruk?

I denne delen gir vi en kort innføring i hvordan man tar i bruk rammeverket.

#### 1) Installer Python-pakken `ssb-dash-framework` i miljøet ditt

```{.bash filename="Terminal"}
poetry add ssb-dash-framework
```

#### 2) Opprett og kjør en `app.py`-fil med følgende kode:

```{.python filename="app.py"}
import os
from ssb_dash_framework import main_layout, app_setup

port = 8070
service_prefix = os.getenv("JUPYTERHUB_SERVICE_PREFIX", "/")
domain = os.getenv("JUPYTERHUB_HTTP_REFERER", None)
theme = "darkly"
app = app_setup(port, service_prefix, theme)

window_list = []

tab_list = []

app.layout = main_layout(window_list, tab_list)

if __name__ == "__main__":
    app.run(
        port=port,
        jupyter_server_url=domain,
        jupyter_mode="tab"
    )
```

Fungerer koden bør en tom dash-applikasjon åpnes.


#### 3) Sett opp variabelvelgeren

Som nevnt er variabelvelgeren en sentral del av rammeverket. Den sørger for at alt henger sammen. Slik setter du den opp:

```{.python filename="app.py"}
from ssb_dash_framework import set_variables # importerer variabelvelgeren

set_variables(["orgnr", "aar"]) # Dette gjør at orgnr og aar er tilgjengelig i applikasjonen din.
start_verdier = { # Valgfritt å ha med, men kan være praktisk for brukervennlighet. Puttes inn i app.layout() funksjonen.
    "orgnr": "971526920",
    "aar": "2020"
}
```

#### 4) Legg til moduler

Moduler er komponenter i applikasjonen din som gir spesifikke funksjoner eller funksjonalitet. Vi legger til modulene EditingTableTab og EditingTableWindow. Første modul viser dataene som en ny fane (litt som RStudio eller nettleser). Med andre modul vil dataene dukke opp som et eget vindu.

Første steg er å importere modulene i `app.py`

```.{python filename="app.py"}
from ssb_dash_framework import EditingTableTab # Tab modulen
from ssb_dash_framework import EditingTableWindow # Vindu modulen
```

```{.python filename="app.py"}

### Konfigurer tab-modulen

def get_data_orgnr(orgnr):
    return df[df['orgnr'] == orgnr]

enhetstabell = EditingTableTab(
    label="Enhetstabell",
    inputs=["orgnr"],
    states=[],
    get_data_func=get_data_orgnr,
    update_table_func=lambda x, *args: x,
    output="aar"
)

tab_list = [
    enhetstabell,
]

### Konfigurer tab-modulen

def get_data_aar(year):
    return df[df['aar'] == year]

aars_tabell = EditingTableWindow(
    label="Komplett årstabell",
    inputs=["aar"],
    states=[],
    get_data_func=get_data_aar,
    update_table_func=lambda x, *args: x,
    output="orgnr"
)

window_list = [
    aars_tabell,
]
```

#### 5) Kjør applikasjonen


```{.python filename = "app.py"}

app.layout = main_layout(window_list, tab_list, default_values = start_verdier)

if __name__ == "__main__":
    app.run(
        port=port,
        jupyter_server_url=domain,
        jupyter_mode="tab"
    )
```