---
title: Google Cloud Console (GCC)
resources: 
  - ../images/gcc-project-selector.mp4
freeze: true
execute:
    echo: false
    include: true
---

```{python}
import sys
import os
sys.path.append("..")

from functions.metadata import get_last_modified

file_path = os.path.abspath('gcc.qmd')
print(get_last_modified(file_path, False))
```

Google Cloud Console (GCC) er et web-basert grensesnitt for å administrere ressurser og tjenester på Google Cloud Platform (GCP). Alle i SSB kan logge seg inn i GCC med sin SSB-bruker. Dapla-team har sjelden mulighet til å opprette nye ressurser fra dette grensesnittet, siden vi ønsker at det skal gjøres med kode. Men det er likevel et nyttig verktøy for å se på ressurser og gjøre endringer på eksisterende ressurser. I SSB bruker bruker vi GCC hovedsakelig til følgende:

- Som en filutforsker for data.
- For å se på loggene til tjenester.
- For å sette opp overføringsjobber med [Transfer Service](./transfer-service.html).

## Innlogging

For å logge inn i GCC så gjør du følgende:

1. Åpne [Google Cloud Console](https://console.cloud.google.com/) i en nettleser. 
2. Logg in med din SSB-bruker. 

Hvis du også har en privat Google-konto som benyttes i samme nettleser, må du noen ganger passe på at du er logget inn med riktig konto. Dette kan du sjekke ved å trykke på profilbildet ditt øverst til høyre i GCC. Hvis du ikke er logget inn med riktig konto, så trykker du på `Logg ut` og logger inn på nytt med riktig konto.



## Prosjektvelger

Etter at du har logget deg på med din SSB-bruker, så må du velge hvilket av ditt teams prosjekter du ønsker å jobbe med. Dette gjør du ved å trykke på prosjektvelgeren øverst til venstre på siden. Vidoen under viser hvordan du velger et prosjekt og lister ut hvilke bøtter som finnes i prosjektet.


{{< video ../images/gcc-project-selector.mp4
    title='How to open a GCP-project in GCC?'
 >}}

## Filutforsker

For å utforske bøtter og filer i et Dapla-team sitt Google-prosjekt så kan man bruke **Cloud Storage**-grensesnittet i GCC. For å bruke denne funksjonaliteten gjør du følgende:

1. Bruk [prosjektvelgeren](./gcc.html#prosjektvelger) til å velge ønsket prosjekt.
2. Deretter søker du opp **Google Storage** i søkefeltet øverst på siden.

Da får du en oversikt over alle bøttene i prosjektet. Velg ønsker bøtte for å utforske innholdet i bøtta.

## Logger

Kommer snart. 

## Transfer Service

Les mer om hvordan man bruker Transfer Service [her](./transfer-service.html).

