# Hurtigstart

Denne siden hjelper deg med å komme raskt i gang med å jobbe på Dapla. Den oppsummerer de viktigste tingene fra de andre kapitlene. 

## Nybegynneren

Logg deg inn i [prod-miljøet på Dapla](https://jupyter.dapla.ssb.no/). Åpne en notebook med `python 3`-kernel og du kan starte å kode med de vanligste python-bibliotekene med en gang. Ønsker du å lese/skrive filen fra/til en bøtte så kan du bruke python-pakken [dapla-toolbelt](./jobbe-med-data.html):

```{.python filename="notebook"}
import dapla as dp

dp.write_pandas(df, "gs://ssb-bucket-name/df.parquet")
```

## Opprett et Dapla-team

Ønsker du å jobbe seriøst med data på Dapla så må du opprette et Dapla-team. Opprettelsen må godkjennes av din nærmeste leder og du søker om det i [Dapla Start Portalen](https://start.dapla.ssb.no/).  
[Les mer.](./hva-er-dapla-team.html)

## Jobbe med kode

For å følge beste-praksis rundt kode er det anbefalt at man oppretter et [ssb-project](./jobbe-med-kode.qmd#opprett-ssb-project) før man starter å kode. Det gir deg et GitHub-repo, en mappestruktur, anbefalt Git-konfigurasjon og muligheten til å installere egne pakker.  
[Les mer.](./jobbe-med-kode.html)

```{.python filename="terminal"}
ssb-project create stat-testprod --github --github-token='blablabla'
```

## Jobbe med data

Du installerer selv de pakkene du ønsker å benytte i koden din. Men lesing og skriving til lagringsbøttene dine gjøres enklest med [dapla-toolbelt](./jobbe-med-data.html).

## Datatilstander

I en statistikkproduksjon så skal dataene lagres i vedtatte datatilstander. Disse er **kildedata**, **inndata**, **klargjorte data**, **statistikkdata** og **utdata**. Alle datatilstander, utenom **inndata**, er obligatoriske datatilstander for alle statistikkproduksjoner.  
[Les mer.](./datatilstander.html)
