# Velkommen {.unnumbered}

Denne manualen tar sikte p친 친 gi SSB-ansatte mulighet til 친 ta i bruk Dapla uten hjelp fra eksperter. Boken er delt i syv kapitler som er kort skildret i denne innledningen, i tillegg til en appendiks, en [blogg](../blog/index.qmd) og eksempel-notebooks. Under hjelp-fanen 칮verst p친 nettsiden finner du blant annet siden [FAQ](../FAQ.html) hvor ofte stilte sp칮rsm친l besvares. I denne boken omtaler vi den gamle produksjonssonen, ofte kalt prodsonen, som **bakke**, og det nye skymilj칮et Google Cloud som **sky**. Det er ikke helt presist men duger for form친lene i denne boken.

::: {.callout-tip}
## Sett i gang p친 bakken!
Det er tilrettelagt for en *treningsarena* i bakkemilj칮et (jupyter lab). Dette milj칮et er nesten identisk med det som m칮ter deg p친 Dapla, med unntak av at du her har tilgang til mange av de gamle systemene og mye mindre 'hestekrefter' i maskinene. Ideen er at SSB-ere ofte vil 칮nske 친 l칝re seg de nye verkt칮yene^[Det som omtales som *nye verkt칮y* vil som regel bety R, Python, Git, GitHub og Jupyterlab.] i kjente og kj칝re omgivelser f칮rst, og deretter flytte et ferdig skrevet produksjonsl칮p til Dapla.
:::

Manualen er delt opp i syv kapitler: F칮rste kapittel handler om Dapla-team. 칀 ha et team er en forutsetningen for 친 drive databehandling p친 platformen. Dermed er det et naturlig f칮rste steg 친 opprette et team.

I andre kapittel, data, forklares blant annet hvordan data leses, lagres og deles. Her tar vi for oss bruk av v친r interne Python-pakke [dapla-toolbelt](https://pypi.org/project/dapla-toolbelt/), og forklarer hva det vil si at data lagres i b칮tter.

Tredje kapittel, kode, tar utgangspunkt i at man skal starte 친 kode opp sin statistikkproduksjon eller kj칮re eksisterende kode. Her dekkes temaer som versjonsh친ndtering p친 github og virtuellle milj칮er i b친de Python og R. Verkt칮yet ssb-project er en viktig del av dette kapitlet.

Fjerde kapittel handler om standarder og beskriver de standardene vi m친 forholde oss til n친r vi driver statistikkproduksjon p친 dapla. Dette inkluderer versjonering av filer, mappestrukturer og filnavn. 

I kapittel fem, metadata, kan du blant annet l칝re om Datadoc - et verkt칮y for 친 dokumentere datasett og variablene som utgj칮r datasettet.

I sjette kapittel kan du l칝re om Dapla Lab: v친r utforsker og platform for 친 kj칮re og skrive kode, og kommunisere med Google Cloud Platform. I skrivende stund er Dapla Lab i beta, og artikkelen dermed uferdig.

I syvende kapittel viser vi til datatjenestene som tilbys p친 Dapla. I dette kapitlet er det artikler om automatisk kildedataprosessering med [kildomaten](kildomaten.qmd), [pseudonymisering](pseudonymisering.qmd), [dapla-statbank-client](statistikkbanken.qmd) og tilgangsstyring med [Dapla Ctrl](dapla-ctrl.qmd).

Til slutt har vi en appendiks med litt forskjellig innhold. Her finnes det artikler om alt fra Altinn 3 til hvordan man kan bidra til denne manualen.

Forh친pentligvis senker denne boken terskelen for 친 ta i bruk Dapla. Kommentarer og 칮nsker vedr칮rende boken tas imot med 친pne armer.

God forn칮yelse游때

::: {.callout-note}
## Vi trenger bidragsytere!
Dapla er i konstant utvikling og det er manualen og! Derfor trenger vi flere bidragsytere til 친 fjerne utdatert informasjon, forbedre eksisterende artikler og skrive nye.

Kunne du tenkt deg 친 bidra? Les om hvordan du kan bidra i [denne artikkelen](./contribution.qmd) i appendiksen.
Har du lyst til 친 bidra, men er ikke helt sikker p친 hva du kan bidra med? Ta kontakt med Team Statistikktjenester!
:::