---
title: Just-in-Time Access
---


*Just-in-Time Access* (JIT) er en applikasjon der [data-admins](./hva-er-dapla-team.html#data-admins) kan gi seg selv midlertidig tilgang til [kildedata](datatilstander.html#kildedata). På Dapla benyttes for dette for å unngå at data-admins har permanent tilgang til sensitive data, siden all kildedata er definert som sensitiv informasjon. *data-admins* må bruke JIT-applikasjonen for å gi seg selv korte, begrunnede tilganger til kildedata ved behov. Den som er ansvarlig for teamet kan monitere i hvilken grad teamets data-admins benytter seg av denne muligheten.

## Hvordan bruke JIT

For å bruke JIT må du være [data-admin](./hva-er-dapla-team.html#data-admins) for teamet som eier kildedataene du ønsker tilgang til. Før du kan jobbe med kildedataene må du gå inn i JIT-applikasjonen og aktivere tilgangen. Det er en applikasjon for prod-miljøet og en for test-miljøet. Du logger deg inn på følgende lenker^[Hvis du jobber fra hjemmekontor må du bruke VPN for å få tilgang til JIT-applikasjonen.]:

| Miljø | Nettadresse                                                                                                         |
| ----- | ------------------------------------------------------------------------------------------------------------------- |
| prod  | <https://jitaccess.dapla.ssb.no/>                                                                                   |
| test  | <https://jitaccess.dapla-test.ssb.no/>                                                                              |
: Nettadresser for de prod- og test-miljøet {#tbl-jit-url}

Trenger du tilgang til kildedata i prod-miljøet^[Prod-miljøet er der man har "ekte" data, mens test-miljøet kun inneholder syntetiske data.] så bruker du lenken fra i første rad @tbl-jit-url. Trenger du tilgang til kildedata i test-miljøet så bruker du lenken fra andre rad @tbl-jit-url.

I nettiden som åpnes blir du bedt om å oppgi følgende:

1. [Prosjekt-id](../faq.qmd#hvordan-finner-jeg-et-google-prosjekt-sin-prosjekt-id) der kildebøtta ligger. 
2. Deretter blir du bedt om å oppgi hvilke tilgangsroller du ønsker aktivert. Se forklaring av rollen i 
3. Deretter velger du hvor lenge tilgangen skal vare. Den kan maksimalt vare i 8 timer. 
4. Deretter må du skrive en begrunnelse for at aktiverer tilgangen. 
5. Til slutt trykker du på **Request access**.

Tilgangen vil deretter være aktiv ila. noen minutter. 

::: {.callout-note}
# Hvordan skal begrunnelsen se ut?
Prøv å gjør begrunnelsen forståelig for andre enn deg selv på det tidspunktet. Den som er ansvarlig for teamet skal kunne forstå begrunnelsen når de ser på loggene. I tillegg vil sentralt i SSB monitere i hvilken grad Dapla-teamene benytter seg av tilgangene. 
:::

| Roller                | Hva?                                                   |
| --------------------- | ------------------------------------------------------ |
| ssb.buckets.list      | Liste ut bøttene i kildeprosjektet.                    |
| storagetransfer.admin | Sette opp jobb med Transfer Service i kildeprosjektet. |
| ssb.bucket.write      | Lese og skrive til kildebøtta.                         |
: De mest relevante tilgangene som kan aktiveres i JIT-applikasjonen {#tbl-jit-roles}