---
title: Klass
date-modified: "01/20/2025"
lightbox: true
---

Klass er SSBs system for dokumentasjon av kodeverk^[Kodeverk er en fellesbetegnelse for klassifikasjoner og kodelister. En klassifikasjon er et mer «formelt» kodeverk som oppfyller flere betingelser, bl.a. at den er normativ og uttømmende. Alle klassifikasjoner i SSB har navn som begynner med Standard for, f.eks. Standard for næringsgruppering eller Standard for kommuneinndeling. Ei kodeliste er ofte skreddersydd for en bestemt statistikk, er ikke normativ og trenger ikke være uttømmende.]. Hensikten er at alle kodeverk skal dokumenteres og oppdateres ett sted (av ansvarlig seksjon), og gjenbrukes av alle som har behov for dem. Ansvarlig seksjon vil da sikre at alle får tak i gyldig versjon (eller en tidligere versjon dersom det er det brukeren trenger).

Alle^[Det finnes kodeverk som ikke kan legges inn i Klass fordi de ikke oppfyller kravene som stilles i den internasjonale modellen som Klass bygger på.] kodeverk som brukes i SSBs statistikkproduksjon skal dokumenteres i Klass. Hvert kodeverk har en eierseksjon, og det er eierseksjonen som har ansvar for å dokumentere, og senere oppdatere, kodeverket. Klass viser hvilke kategorier de ulike kodeverkene inneholder på en gitt dato, eller i løpet av en gitt tidsperiode, hvordan kategoriene endrer seg over tid (f.eks. endring i kommuneinndelingen [Standard for kommuneinndeling](https://www.ssb.no/klass/klassifikasjoner/131/endringer)). I tillegg kan Klass vise mappingen mellom to ulike kodeverk (f.eks mellom politidistrikt og kommuner [Standard for politidistrikt](https://www.ssb.no/klass/klassifikasjoner/109/korrespondanser/1783)). En kan også lage en variant av et kodeverk, der en f.eks. aggregerer ulike koder i det opprinnelige kodeverket (se f.eks. [Standard for næringsgruppering (SN)](https://www.ssb.no/klass/klassifikasjoner/6/varianter/1121) som er en variant der kodene i Standard for næringsgruppering er blitt aggregert). Kodeverkene kan gjenbrukes av alle som trenger dem, både SSB-ansatte og eksterne brukere. Mange av kodeverkene i Klass, f.eks. Standard for kommuneinndeling og Standard for næringsgruppering, gjenbrukes i stor grad både av interne og eksterne brukere.

Det kan refereres til Klass både fra Vardef og Datadoc.

Kodeverkene kan hentes ut [via et API](https://data.ssb.no/api/klass/v1/api-guide.html) eller lastes ned i csv-format. API-er det mest fleksible å bruke. Her kan en f.eks. hente ut kodeverket slik det var på en bestemt dato, i et bestemt tidsrom, hvilke endringer som har skjedd innen et visst tidsrom og korrespondansetabeller som viser mappingen mellom to ulike kodeverk.  Det finnes også veiledning til bruk av Klass i statistikkproduksjonen (sas, R og Python) her: [Bruk av Klass i statistikkproduksjonen](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Oversikt-over-m%C3%A5ter-%C3%A5-tilpasse-Klass-til-produksjon.aspx).
