---
title: KuDoc datamodell
date-modified: 06/23/2026
lightbox: true
---

I KuDoc er det foreløpig to sentrale konsepter: (data)**innsamling** og innsamlings**instrument**.

For en bestemt innsamling kan det bli tatt i bruk én eller flere instrumenter. Instrumentene brukt for en innsamling kan enten være av én og samme type – for eksempel to eller flere Altinn3-skjemaer (f.eks. et skjema for bedrifter og et annet for foretak) – eller det kan være forskjellige typer instrumenter brukt i én og samme innsamling – for eksempel Altinn3-skjema for de fleste foretak, pluss API-er for innhenting av data fra noen utvalgte, store foretak, som kan tilby en slik løsning.

Informasjonselementer som inngår i KuDoc er delt i tre nivåer:

1. Informasjonselementer som relaterer seg til innsamlingen som helhet.
2. Opplysninger for instrument, der informasjonselementene er felles for alle typer instrumenter (altså: feltene er like / gjelder for alle instrumenter, uavhengig av instrumenttype – men ikke verdiene i de feltene: disse er egne for hvert enkelt instrument).
3. Informasjonselementer for instrument som bare er aktuelle for en bestemt instrumenttype – f.eks. opplysninger om intervju-modus (CATI | CAPI | CAWI m.m.) som kun gjelder for instrumenter av type spørreskjema for personer, mens RA/RS-skjemanummer (jf. [Kodeliste for RA/RS-nummer (skjema)](https://www.ssb.no/klass/klassifikasjoner/916)) kun er relevant for innsamlinger vha. skjemaer i Altinn.

De to første gruppene informasjonselementer (1 og 2) er beskrevet i underkapitlene [Innsamling](#innsamling) og hhv. [Instrument - alle typer](#instrument-alle-typer).

Bruk av symboler:

- [*Påkrevd for utkast*]{style="background-color:#ffd699;"} = informasjonselementet er obligatorisk i både status *Draft* og *Publisert*
- [*Påkrevd ved publisering*]{style="background-color:#cce5ff;"} = obligatorisk kun for status *Publisert*

(for forklaring av status Draft vs. Publisert, se kapittel [Legge inn opplysninger](./kudoc-data-entry-via-gui.qmd))

## Innsamling

### Innsamlingsnummer

[*Påkrevd for utkast*]{style="background-color:#ffd699;"}

Blir tildelt automatisk ved opprettelse av ny innsamling i KuDoc. Nummeret er **unikt** på tvers av alle innsamlinger.

### Navn på innsamlingen

[*Påkrevd for utkast*]{style="background-color:#ffd699;"}

Et beskrivende navn på innsamlingen, som skal være forståelig for mennesker (og gjerne gjenkjennbart i SSB). Navnet må være **unikt** på tvers av alle innsamlinger i KuDoc. Kan editeres i etterkant.

Hvis du blir tvungen til å dele en datainnsamling som du har ansvar for, i flere separate innsamling-entry'er for registrering i KuDoc (som kan være tilfellet f.eks. hvis det er involvert flere frekvenser), kan du gjerne bruke det navnet som deres seksjon/team er vant til, med suffiks som vil skille entry'ene fra hverandre (f.eks. "Innsamling X - årlig", "Innsamling X - kvartalsvis" osv.).

### Mottakende Dapla-team

[*Påkrevd for utkast*]{style="background-color:#ffd699;"}

Verdi i denne velges fra listen over tilgjengelige [Dapla-team](./hva-er-dapla-team.qmd) fra [Dapla Ctrl](./dapla-ctrl.qmd#teamoversikt). Valget blir styrende for hvilket team sin **kildebøtte** som data fra innsamlingen skal legges i.

### Grunngivende statistikkprodukt

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

Statistisk produkt (statistikk, indeks e.l.) som utgjør opprinnelig formål med å etablere innsamlingen. Gjerne det produktet som fremgår i et DM-dokument som knytter sammen en statistikk med innsamlingen (f.eks. vedtak om etablering av statistikk, e.a. i DM).

Angis ved **kortnavn**, som velges fra liste fra Statistikkregisteret. Obligatorisk først ved *publisering* i KuDoc, og kun for innsamlinger med offisiell statistikk som formål (dvs. unntak for innsamlinger som merkes av som markedsoppdrag - jf. neste felt).

Med utgangspunkt i det angitte kortnavnet til statistikken, blir det hentet inn noen flere opplysninger fra Statistikkregisteret og vist i KuDoc, som: **fullt navn** til statistikkproduktet, og **statistikkansvarlig**(e) med **kontaktinfo**.

### Oppdragstype

To-valgs felt: **Offisiell statistikk** vs. **Markedsoppdrag/forskning/uttesting**. Den første verdien fordrer krav om at det må angis grunngivende statistikkprodukt (jf. forrige felt).

### Lenke til utvalgsplan

Url-adresse til der utvalgsplan for innsamlingen kan finnes (enten i en strukturert form eller kun som et tekstdokument).

### Leverandører av data

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

Liste med verdier fra [Kodeliste for SSB-datakilder](https://www.ssb.no/klass/klassifikasjoner/712). Angir konkrete kilder/leverandører - f.eks. NAV, Utdanningsdirektoratet, eller samlebegrep for SSBs egne utvalgsundersøkelser (–> kodeverdi 67).

Verdier valgt i listen her på innsamlings-nivå, utgjør tillatte verdier for *Instrument-datakilde* på de enkelte instrumentene som er knyttet til innsamlingen (se neste avsnitt: [Instrument](#instrument-alle-typer)).

### Enhetstyper for rapporteringsenheter

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

Liste med verdier fra [KLASS kodeliste for enhetstyper](https://www.ssb.no/klass/klassifikasjoner/702), dog begrenset til Foretak, Bedrift eller Person. Angir hvilke typer enheter som er rapporteringsenheter i innsamlingen.

### Særlige kategorier av data

Avkryssingsboks for å angi om innsamlingen inkluderer særlige kategorier av personopplysninger, iht. **GDPR art. 9**. Default er **Nei**, må endres til Ja hvis det er tilfellet.

### Innkvitteringsfrekvens

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

Frekvensen som data samles inn med og kontrolleres for at alle enheter har rapportert. Velges fra liste med følgende verdier: Engangs | Hvert 10. år | Hvert 5. år | Hvert 4. år | Hvert 3. år | Hvert 2. år | Årlig | Halvårlig | Kvartalsvis | Termin (= hverannen mnd.) | Månedlig | Ukentlig.

### Oppstarts-/initieringsdato for innsamling

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

For ***planlagte innsamlinger:*** foreslått startdato for innsamlingen, dvs. når datainnsamlingen skal påstartes/initieres for første gang.

For ***eksisterende innsamlinger:*** den tidligste kjente datoen for når innsamlingen ble kjørt for første gang. Nb. hvis nyere tidspunkter for kjøring av innsamlingen ikke lenger stemmer med tidsmønsteret: *(den faktiske) Oppstartsdato + N x [frekvens](#innkvitteringsfrekvens)* (f.eks. en årlig innsamling som opprinnelig var kjørt på våren, men senere flyttet til høsten, e.l.), da bør datoen som angis justeres frem ("jukses litt") slik at de nåværende innsamlings-forekomstene stemmer med mønsteret – slik at mønsteret kan brukes for å anslå og planlegge / omtrentlig beramme nye, kommende kjøringer av innsamlingen.

### Avtalt/kommunisert innrapporteringsfrist

Frist for innlevering, angitt i *antall dager etter oppstartsdato* (nb. forstått som en generell regel/anvisning - ikke hensyntatt anledningsvise justeringer for fridager, ferier e.l.).

### Siste, endelig innrapporteringsfrist

Siste, endelige frist for innlevering *i antall dager etter oppstartsdato*, før man må gå over til produksjonsfaser (inkludert purringer og utvidede frister).

## Instrument (alle typer)

### Instrumenttype

[*Påkrevd for utkast*]{style="background-color:#ffd699;"}

I nåværende versjon er det implementert tre valgmuligheter: **Spørreundersøkelse for personer** (vha. Blaise, web og/el. app) | **Skjema i Altinn** | **API**.

### Leverandør av data for instrumentet

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

En enkeltverdi fra [Kodeliste for SSB-datakilder](https://www.ssb.no/klass/klassifikasjoner/712). Valgbare verdier her er bestemt av verdier lagt inn i tilsvarende felt på Innsamling-nivået (jf. [Leverandører av data](#Leverandører-av-data) i forrige avsnitt).

### Mottaksfrekvens

[*Påkrevd ved publisering*]{style="background-color:#cce5ff;"}

Hvor ofte hentes/mottas data vha. dette instrumentet. Verdier som kan velges er de samme som i feltet [Innkvitteringsfrekvens](#innkvitteringsfrekvens) for innsamling, og i tillegg: ... | Daglig | Kontinuerlig (dvs. strømming) | Etter behov ("ad hoc").

### Ekstern kontaktperson (navn)

Kontaktperson for innsamlingen med dette instrumentet hos leverandøren av data.

### Ekstern kontaktperson, e-post

E-post adresse til kontaktpersonen hos leverandøren av data.

### Intern kontaktperson (navn)

Velges fra listen over team-medlemmer i Dapla-teamet som ble angitt på Innsamling-nivå (jf. [Mottakende Dapla-team](#Mottakende-Dapla-team)). For den valgte personen blir også e-post adresse vist, avlest fra Dapla Ctrl.

### Produktkode evt. arbeidsordre

Produktkode/arbeidsordre knyttet til innsamlingen (enten for innsamlingen som helhet, eller spesifikt for den innsamling-delen som utføres vha. det aktuelle instrumentet). Kan angis enten med 5 siffer dvs. kun prosjekt-/produktkode, eller med 7 siffer dvs. inkludert også sifre for fullstendig arbeidsordre.
