---
title: KuDoc
date-modified: 06/11/2026
lightbox: true
---

**KuDoc** er SSBs metadatasystem for **K**ilde- og **u**tvalgsdokumentasjon. Formålet med registeret er å gi oversikt over hvilke datakilder og utvalg som SSB mottar data fra, og som ligger til grunn for statistiske analyser eller undersøkelser.

Dette er første gang at opplysninger om innsamlinger av data inn til SSB skal samles i et felles enhetlig system på tvers av avdelinger og innsamlingsmetoder. Det gjør at registeret må fylles inn med informasjon helt fra bunn. Av den grunn er systemet gjort tilgjengelig allerede i tidlig versjon: MVP (Minimum Viable Product). Formålet med dette er at aktuelle grupper av brukere kan begynne å fylle inn data om innsamlinger som de benytter seg av, så snart som mulig.  

I den nåværende systemversjonen gjelder det følgende begrensninger:  

* Opplysninger for utvalgsplan er kun implementert på et meget forenklet vis: gjennom en lenke til et dokument der utvalgsplan for innsamlingen er beskrevet  
(senere vil utvalgte opplysninger for utvalgsplanlegging bli strukturert i egne felt)  

* Kun tre typer av innsamlingsinstrumenter er inkludert for tiden:  
skjemainnrapporteringer via Altinn3,  
spørreundersøkelser for personer (vha. Blaise og/eller app),\ \ og  
innsamlinger vha. API  

* Det kan kun registreres én frekvens per innsamling (t.o. noe som er det faktiske tilfellet for de aller fleste innsamlinger i SSB - så det er kun noen veldig få innsamlinger som evt. vil måtte vente med innregistrering på grunn av dette)  

* Historikk-oversikt er ikke implementert