---
title: Legge inn opplysninger manuelt via GUI
date-modified: 06/24/2026
lightbox: true
---

Ved innføring av opplysninger inn i KuDoc, vil man alltid starte i *status Draft*.  
I denne tilstanden, er det kun noen få opplysninger som er obligatoriske, mens i alle andre felter kan det "kladdes" fritt uten at konsistensregler for entry'et blir validert. Disse få informasjonselementene som er obligatoriske allerede i status *Draft*, er merket som [Påkrevd for utkast]{style="background-color:#ffd699;"}

Når man er ferdig med innlegging av opplysninger i KuDoc og vil gjøre disse åpent tilgjengelige for hele SSB, skal man gå over i *status Publisert*.  
I denne tilstanden er det krav om flere korrekt og konsistent utfylte opplysninger enn mens i Draft; informasjonselementer som er obligatoriske for å gå over til *Publisert* (selv om ikke påkrevd mens ennå i Draft) er merket med [Påkrevd ved publisering]{style="background-color:#cce5ff;"}

For mer detaljert informasjon om hvilke opplysninger som er obligatoriske i de ulike statusene, se kapittel [KuDoc datamodell](./kudoc-model.qmd) \ eller direkte i GUI:

Team som ønsker å registrere sine datainnsamlinger i KuDoc, kan gjøre det via GUI i [produksjonsversjon](https://kudoc.intern.ssb.no/).  
Om du foretrekker å først teste og prøve deg frem, kan du bruke [QA-versjon](https://qa-kudoc-frontend.intern.test.ssb.no/).  
Ved spørsmål eller behov for hjelp, ta gjerne kontakt med noen av oss i [team Datafangsttjenester](https://dapla-ctrl.intern.ssb.no/team/dftjen/members).  

I begge GUI-versjonene kan du finne en lenke med mulighet å melde eventuelle opplevde feil, mangler, eller forslag til forbedringer.  
KuDoc er et helt nytt system, som medio 2026 blir satt i produksjon i aller første versjon. Det skal videreutvikles kontinuerlig, og vi vil sette stor pris på tilbakemeldinger som vil hjelpe oss å gjøre systemet bedre.