---
title: Kvalitet i kode og koding (KVAKK)
date-modified: "11/29/2024"
---

**KVAKK** er en tverrfaglig gruppe som utarbeider regler, anbefalinger og veiledninger for god prakis for jobbing med kode og koding.
Gruppa har mandat fra DM og består av representanter fra alle statistikkavdelinger, forskning, metode og IT.

Gruppa jobber temabasert og publiserer
[regler, anbefalinger og veiledninger](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3261497397/Kvalitet+i+kode+og+koding)
for hvert tema under beste praksis området på Confluence. Regler skal følges, med mindre man har en dokumentert begrunnelse på hvorfor regelen avvikes. Følgende regler er fastsatt i SSB:

- [All produksjonskode skal være under versjonskontroll i GitHub](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3041492993/Regler+og+anbefalinger+for+versjonskontroll+med+Git#R-001-Regel:-All-produksjonskode-skal-v%C3%A6re-under-versjonskontroll-i-GitHub.)
- [Kildekode i GitHub skal ikke inneholde ukrypterte passord eller hemmeligheter](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3041492993/Regler+og+anbefalinger+for+versjonskontroll+med+Git#R-003-Regel%3A-Kildekode-i-GitHub-skal-ikke-inneholde-ukrypterte-passord-eller-hemmeligheter.)
- [Git-klienter skal konfigureres slik at resultat fra kjøringer i Jupyter Notebooks ikke lagres på GitHub](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3041492993/Regler+og+anbefalinger+for+versjonskontroll+med+Git#R-004-Regel%3A-Git-klienter-skal-konfigureres-slik-at-resultat-fra-kj%C3%B8ringer-i-Jupyter-Notebooks-ikke-lagres-p%C3%A5-GitHub.)
- [Alle biblioteker skal ha en eier](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3569778806/Regler+og+anbefalinger+for+gjenbruk#R-040-Regel%3A-Alle-biblioteker-skal-ha-en-eier)
- [Bruk SSB-mal for PyPI-biblioteker når du skal lage et python-bibliotek](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3569778806/Regler+og+anbefalinger+for+gjenbruk#R-041-Regel%3A-Bruk-SSB-mal-for-PyPI-biblioteker-n%C3%A5r-du-skal-lage-et-python-bibliotek)
- [Grensesnittet til biblioteket skal være dokumentert](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3569778806/Regler+og+anbefalinger+for+gjenbruk#R-042-Regel%3A-Grensesnittet-til-biblioteket-skal-v%C3%A6re-dokumentert)
- [ Alle biblioteker skal ha tilhørende tester](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3569778806/Regler+og+anbefalinger+for+gjenbruk#R-043-Regel%3A-Alle-biblioteker-skal-ha-tilh%C3%B8rende-tester)
- [All produksjonskode skal lagres i et format som støtter kodeanalyse](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3911745551/Regler+og+anbefalinger+for+test+og+kodekvalitet#R-061-Regel%3A-All-produksjonskode-skal-lagres-i-et-format-som-st%C3%B8tter-kodeanalyse.)

Anbefalinger er god praksis som de fleste bør følge. Disse finner du på KVAKKs sider om [regler, anbefalinger og veiledninger](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3261497397/Kvalitet+i+kode+og+koding).

Du finner mer informasjon om KVAKK, hvem som er med og arbeidet deres på [KVAKK-siden](https://statistics-norway.atlassian.net/wiki/spaces/KOD/overview).


