---
title: "Standarder"
date-modified: "01/07/2025"
---

Når man driver statistikkproduksjon er det flere regler man må forholde seg til.

**Standardutvalget** står for utarbeidingen av flere av disse reglene og standardene på Dapla, for eksempel navnestandarden som er beskrevet i artikkelen [navnestandard](navnestandard.qmd).

:::{.callout-note collapse=true}
### Kort om standardutvalget!

* Ansvarlig for det sentrale standardiseringsarbeidet knyttet til bruk og gjenbruk av data i SSB.
* Beslutningsmydnighet fra DM, men prinsipielle saker, og saker med store konsekvenser, sendes til DM for vedtak.
* Utvikler hovedsaklig *obligatoriske* standarder, men statistikkprodusenter oppfordres også til å gjøre seg kjent med anbefalingene.
* Lenke: [Standardutvalgets side på byrånettet](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Standardutvalget.aspx#standardutvalgets-arbeid%2c-mandat-og-medlemmer)
* Lenke: [Vedtak fra Standardutvalget](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Vedtak-fra-Standardutvalget.aspx)
:::

Denne artikkelen er i stor grad basert på [standardutvalgets mandat](https://ssbno.sharepoint.com/sites/Internedokumenter/Delte%20dokumenter/Forms/AllItems.aspx?id=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023%2F2023%2D15%20Mandat%20standardutvalget%2Epdf&parent=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023) og [standardutvalgets side på byrånettet](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Standardutvalget.aspx#standardutvalgets-arbeid%2c-mandat-og-medlemmer).

### Standardutvalget

Standardutvalget har ansvar for det sentrale standardiseringsarbeidet knyttet til bruk og gjenbruk av data i SSB. Alle avdelinger er representert med unntak av avdeling 100. [Standardutvalgets side på byrånettet](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Standardutvalget.aspx#standardutvalgets-arbeid%2c-mandat-og-medlemmer) inneholder en oversikt over utvalgsmedlemmene.

Formålet med utvalget, slik det er beskrevet i [mandatet fra 2023](https://ssbno.sharepoint.com/sites/Internedokumenter/Delte%20dokumenter/Forms/AllItems.aspx?id=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023%2F2023%2D15%20Mandat%20standardutvalget%2Epdf&parent=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023), er å *legge grunnlag for effektiv bruk og gjenbruk av data som SSB samler inn, bearbeider
og forvalter*.

Standardutvalget har beslutningsmyndighet delegert fra DM og kan dermed vedta krav, regler, anbefalinger eller obligatoriske standarder.

##### Hvilke områder jobber standardutvalget med?

Standardutvalget utvikler standarder innenfor **følgende områder**:

* Kodeverk (klassifikasjoner og kodelister)
* Variabler og variabelnavn
* Enhetstyper
* Navngivning, versjonering, dokumentasjon og lagring av datasett og populasjoner i alle ledd i produksjonsprosessen
* Kvalitetsindikatorer
* Prosessdata
* Datatilstander
* Informasjonsmodeller

Standardutvalget har *ikke* ansvar for standarder innenfor koding og statistiske metoder. Det håndteres av KVAKK (Kvalitet i kode og koding) og s811 - Seksjon for metoder. 

### Hvilke standarder finnes?


##### 1. **DataDoc** - dokumentasjon av datasett

* [DataDoc - Krav til dokumentasjon av datasett på Dapla (Confluence)](https://statistics-norway.atlassian.net/wiki/spaces/MPD/pages/3039133732/DataDoc+-+Krav+til+dokumentasjon+av+datasett+p+Dapla)
* [Datadoc-editor - Artikkel i Dapla-manualen](datadoc.qmd)

##### 2. **Datatilstander** i SSB

* [Datatilstander - Artikkel i Dapla-manualen](datatilstander.qmd)
* [Interne dokumenter - Datatilstander, skrevet av Standardutvalget](https://ssbno.sharepoint.com/sites/Internedokumenter/Delte%20dokumenter/Forms/AllItems.aspx?id=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023%2F2023%2D14%20Datatilstander%20i%20SSB%2Epdf&parent=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023)

![En grafisk fremstilling av forskjellene mellom datatilstandene i SSB [@datatilstander2].](../images/datatilstander.png){fig-alt="Figur som viser ulikhetene mellom datatilstandene som er definert i SSB." width="100%" #fig-datatilstander}

##### 3. **VarDef** - dokumentasjon av variabler

* [VarDef - Confluence-side](https://statistics-norway.atlassian.net/wiki/spaces/MPD/pages/3009839199/VarDef+-+Krav+til+dokumentasjon+av+variabler)

##### 4. **Standardformater** for lagring av data

* [Standardformater - Confluence-side](https://statistics-norway.atlassian.net/wiki/spaces/MPD/pages/2953084957/Standardformater)

##### 5. **Navnestandard** for henholdsvis:

* Enhetstypeidentifikatorer - [DM-vedtak (internet dokument)](https://ssbno.sharepoint.com/sites/A20-Standardutvalget/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FA20%2DStandardutvalget%2FShared%20Documents%2FGeneral%2FM%C3%B8ter%2F2022%2F20221201%2F2023%2D1%5FDM%2Dgodkj%2DEnhetstypeIDnavn%2Epdf&parent=%2Fsites%2FA20%2DStandardutvalget%2FShared%20Documents%2FGeneral%2FM%C3%B8ter%2F2022%2F20221201)
* GitHub repoer - [Internt dokument](https://ssbno.sharepoint.com/:w:/r/sites/A20-Standardutvalget/_layouts/15/Doc.aspx?sourcedoc=%7BC20FDE49-C24A-49C5-A9AB-4251DE8EAE16%7D&file=Navnestandard_for_GitHub_repoer_oppdatert_endelig.docx&action=default&mobileredirect=true)
* Nøkkelvariabler (*anbefaling*) - [Byrånettside](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Vedtak-fra-Standardutvalget.aspx#standardnavn-for-n%C3%B8kkelvariabler)
* Datasett - [Dapla-manualen: Navnestandard (og versjonering)](navnestandard.qmd)

##### 6. **Kvalitetsindikatorer**

* Standardutvalget har definert et sett med anbefalte kvalitetsindikatorer for statistikkproduksjon - særlig kvantitative indikatorer
* Internt dokument - [Anbefalte kvalitetsindikatorer i statistikkproduksjonen](https://ssbno.sharepoint.com/:w:/r/sites/A20-Standardutvalget/_layouts/15/Doc.aspx?sourcedoc=%7B32459635-A4B4-4913-BFFC-E549DC911512%7D&file=2022_4_kvalitetsindikatorer%20su%200922%20v2.docx&action=default&mobileredirect=true&web=1)
* Internt dokument - [Mal for dokumentasjon av kvalitetsindikatorer](https://ssbno.sharepoint.com/:w:/r/sites/A20-Standardutvalget/_layouts/15/Doc.aspx?sourcedoc=%7B725E877E-8E35-46B1-8B93-F7B03C27366D%7D&file=2022_4_Vedlegg_Dokumentasjon%20av%20kvalitetsindikatorer%20v3.docx&action=default&mobileredirect=true&web=1)

##### 7. **Editering** - prinsipper og retningslinjer

* Offentlig dokument - [Prinsipper og retningslinjer for dataeditering](https://www.ssb.no/teknologi-og-innovasjon/informasjons-og-kommunikasjonsteknologi-ikt/artikler/prinsipper-og-retningslinjer-for-dataeditering/_/attachment/inline/491f2050-b6aa-4ca0-a039-3fa9d6d5f962:86b99f7655bb1bc97abcdf91274a844314fc85d8/NOT2023-49.pdf)
* Dokumentet lenket i punktet over inneholder ni prinsipper for editering i SSB, blant annet:
    - Formålet med dataediteringen skal være klart formulert
    - Kontrollene, kontrollustlagene og endringene skal være veldokumenterte
    - Automatiser editeringsprosessen så mye som mulig

##### 8. **Kodelister** (*anbefaling*)

* Les om de anbefalte standardiserinenge i [byrånettsiden for standardutvalgets vedtak](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Vedtak-fra-Standardutvalget.aspx#standardisering-av-kodelister)
