---
title: "Standarder"
date-modified: "12/03/2024"
---

Når man driver statistikkproduksjon er det flere regler man må forholde seg til.

**Standardutvalget** står for utarbeidingen av flere av disse reglene og standardene på Dapla, for eksempel navnestandarden som er beskrevet i artikkelen [navnestandard](navnestandard.qmd).

### Standardutvalget

Standardutvalget har ansvaret for det sentrale standardiseringsarbeidet i SSB. Alle avdelinger er representert i utvalget med unntak av avdeling 100. [Standardutvalgets side på byrånettet](https://ssbno.sharepoint.com/sites/Avdelingerutvalgograd/SitePages/Standardutvalget.aspx#standardutvalgets-arbeid%2c-mandat-og-medlemmer) inneholder en oversikt over utvalgsmedlemmene.

Formålet med utvalget, slik det er beskrevet i [mandatet fra 2023](https://ssbno.sharepoint.com/sites/Internedokumenter/Delte%20dokumenter/Forms/AllItems.aspx?id=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023%2F2023%2D15%20Mandat%20standardutvalget%2Epdf&parent=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023), er å *legge grunnlag for effektiv bruk og gjenbruk av data som SSB samler inn, bearbeider
og forvalter*.

Standardutvalget har beslutningsmyndighet delegert fra DM og kan dermed vedta krav, regler eller obligatoriske standarder.

### Hvilke standarder finnes?

