---
title: Vardef
date-modified: "01/20/2025"
lightbox: true
---

**Vardef** er SSBs system for dokumentasjon av variabler. Hensikten med Vardef er at alle variabler i SSB skal dokumenteres og oppdateres ett sted (av ansvarlig Dapla-team) og gjenbrukes av alle som har behov for dem.

Vardef skal inneholde all nødvendig informasjon om en variabel. Mens Datadoc dokumenterer variabelforekomstene, dvs. enkeltvariablene i et datasett^[Dette er noe vi ønsker å unngå på Dapla, det er best for brukerne om samme variabelforekomst har samme navn i alle datasett der den brukes. Dette vil ikke være noe krav, men dersom variabelforekomstnavnet er det samme som kortnavnet til tilhørende variabel i Vardef, vil variabelforekomsten i Datadoc kunne lenkes maskinelt til riktig variabeldefinisjon i Vardef. Dermed slipper en mye manuelt arbeid.], skal Vardef dokumentere de mer overordnede beskrivelsene av en variabel. I Vardef er det variabler som gjenbrukes, enten på tvers i SSB, eller flere ganger over tid i samme statistikk, som skal dokumenteres. Et eksempel er f.eks. variabelen «organisasjonsnummer» som vil være definert i Vardef, slik at beskrivelsen kan gjenbrukes i alle datafiler der variabelforekomsten organisasjonsnummer inngår. I SSB har ofte organisasjonsnummer ulike navn i ulike datasett , men når alle variablene er knyttet til samme Vardef-variabel, kan brukerne likevel forstå at det er samme variabel.

I Datadoc har en mulighet for å presisere en variabel som refereres til i Vardef. Vi kan f.eks. ha variabelen «Yrkesinntekt» som brukes både i datasett A og B.  Selve definisjonen hentes da fra Vardef og er dermed den samme i begge datasett. Men så kan det være presiseringer en må gjøre i Datadoc for hver variabelforekomst, f.eks. at yrkesinntekt i datasett A måles i kroner, mens den i datasett B måles i 1000 kroner.

Dersom Vardef-variabelen er en kvalitativ variabel (har verdier som hentes fra et kodeverk), skal variabelen referere til tilhørende kodeverk i Klass. F.eks. skal variabelen «Sivilstand» som har definisjonen «Variabelen viser en persons stilling ihht ekteskapslovgivningen», referere til «Standard for sivilstand» i Klass som viser hvilke verdier (kategorier) variabelen kan anta.
