---
title: Datamodell
date-modified: 01/13/2026
lightbox: true
---

Tegnforklaring:

- ✅ informasjonselementen er obligatorisk
- 🌐 det internasjonale navnet for informasjonselementet som er benyttet internt i Vardef
- ℹ️ informasjonselementet er ikke obligatorisk. Det betyr ikke at det er helt nødvendig i enkelte tilfeller, bare at Vardef ikke håndhever det.

Det angis også om informasjonsfeltet kan endres (patches) etter publisering. Publisering gjelder her både intern og ekstern publisering. Før en variabel kan publiseres eksternt, må følgende felt være fylt ut både på bokmål, nynorsk og engelsk: navn, definisjon, ev. kommentar og kontakt/tittel.


### Navn
🌐 *name*

**nb** | **nn** | **en**

✅

Angir navnet til variabelen. Navnet skal være forståelig for mennesker (ikke kun forkortelser) slik at det er søkbart. Navnet skal fylles ut på både bokmål, nynorsk og engelsk.

Navn kan endres etter publisering (f.eks. for å korrigere skrivefeil), men generelt bør navneendring unngås etter publisering. Dersom navnet endres, men variabelen ellers er den samme, bør en heller lage en ny gyldighetsperiode (se forklaring under definisjon) for variabelen.

::: {.callout-tip collapse="true"}
## Eksempler

Eksempel 1:

> Landbakgrunn

Eksempel 2:

> Kapitalinntekter

Eksempel 3:

> Ordretilgang, bygg og anlegg

:::


---

### Kortnavn

🌐 *short_name*

✅

Angir variabelens kortnavn. Kortnavn er som regel et teknisk forkortet navn som er egnet som variabel(kolonne)navn i et datasett. Følgende retningslinjer gjelder for kortnavn i Vardef:

- må være unikt.
- minimumslengde på 2 tegn.
- kun små bokstaver (a-z).
- kan inneholde tall (0-9).
- kan inneholde _ (understrek).
- æ, ø og å er IKKE tillat. Anbefalt at disse erstattes med ae, oe og aa.
- dersom det brukes generiske navn som «kilde» eller «kode» skal variabelen spesifisere vha. suffiks, f.eks. kilde_innt
- prefiks og suffiks kan brukes for å gjøre et kortnavn unikt, f.eks. pers_innt og hush_innt.
- kan ikke være en av de reserverte kortnavnene i SSB (se boks under)

Kortnavnet kan ikke endres etter publisering.



::: {.callout-important collapse="true"}
## Reserverte kortnavn

Etter vedtak i Standardutvalget er noen kortnavn reservert som standard-kortnavn for noen bestemte variabler, og skal derfor ikke brukes av andre. Se oversikt over reserverte kortnavn i @tbl-short_names.

| Reserverte kortnavn              |
|------------------------|
| anloep_id             |
| bruksenhet_id         |
| bygg_id               |
| bygningsstatus        |
| bygningstype          |
| familie_nr            |
| fnr^[**fnr** er et reservert kortnavn for variabelen fødselsnummer.]                  |
| foedselsdato          |
| matrikkelenhet_id     |
| hush_nr               |
| isin                  |
| kjoenn                |
| komm_nr               |
| kurs_id               |
| lovbrudd_id           |
| pers_id               |
| reg_nr                |
| skade_id              |
| trafikkulykke_id      |
| fylke_nr              |
: Oversikt over reserverte kortnavn {#tbl-short_names}

:::

::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på kortnavn for variabeldefinisjonen med [Navn](#navn) *Lønnsinntekter*:

> wloenn

Eksempel på kortnavn for variabeldefinisjonen med [Navn](#navn) *Landbakgrunn*:

> landbak

:::



---

### Definisjon

🌐 *definition*

**nb** | **nn** | **en**

✅

Angir hva variabelen betyr på en så kort og presis måte som mulig. Mer utfyllende opplysninger kan legges i Merknad-feltet.

Definisjon kan endres etter publisering (f.eks. korrigering av skrivefeil).

Hvis det legges inn større endring i definisjonen, skal det opprettes en ny gyldighetsperiode. Dette gjøres ved å sette en ny gyldig f.o.m.-dato. Da vil gyldig t.o.m. for foregående gyldighetsperiode automatisk settes til  gyldig f.o.m.-dato (ny gyldighetsperiode) minus en dag.

Et eksempel på en større endring som skaper en ny gyldighetsperiode, er variabelen «landbakgrunn» som i gyldighetsperioden f.o.m. 1994-01-01, kun har foreldrenes fødeland med i definisjonen, men som i gyldighetsperioden f.o.m. 2003-01-01 også har med besteforeldrenes fødeland.



::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på definisjon for variabeldefinisjon med [Navn](#navn) *Sivilstand*:

> Viser en persons stilling i henhold til ekteskapslovgivningen.

Eksempel på definisjon for variabeldefinisjon med [Navn](#navn) *Kapitalinntekter*:

> Omfatter renteinntekter, aksjeutbytte, realisasjonsgevinster og andre kapitalinntekter i løpet av kalenderåret. Til fradrag kommer årets realisasjonstap

Eksempel på definisjon for variabeldefinisjon med [Navn](#navn) *Ordretilgangen, bygg og anlegg*:

> Verdien av nye ordrer bedriften har mottatt i løpet av kvartalet. Inkluderer også ordrer fullførte i løpet av samme kvartal. Verdien er kontraktsummen eksklusive merverdiavgifter, men inklusive eventuelle produksjons- og omsetningsavgifter.


:::

::: {.callout-tip collapse="true"}
## Hvordan skrive en definisjon?

Følg disse anbefalingene for å skrive en god variabeldefinisjon:

- Start teksten med å variabelens navn. F.eks.:
    - **Landbakgrunn** beskriver en persons tilknytning til utlandet...
    - **Arbeidsledig** beskriver personer uten inntektsgivende arbeid som forsøkte å skaffe seg slikt arbeid...
- Bruk klart språk og vær presis.
- Ingen sirkeldefinisjoner.
- Ta med eksempler hvis det er relevant og øker forståelsen.
- Vis ev. til andre variabler som brukes i definisjonen.
- Hvis mulig, la definisjonen være kort.
- Vanligvis bør populasjon og tidsangivelser utelates fra definisjonen.
- Ved presisering i variabelnavn anbefales komma, f.eks. «Forbruksutgifter, reise».

:::

---

### Kodeverkets URI

🌐 *classification_reference*

ℹ️ (ikke obligatorisk men skal oppgis dersom variabelen benytter et kodeverk)

Angir referansen til kodeverk (klassifikasjon eller kodeliste) i [Klass](https://www.ssb.no/klass/) som beskriver verdiene variabelen kan anta. En skal ikke legge inn hele URI-en, kun id-en for kodeverket. Dette feltet er kun relevant for kvalitative variabler, dvs. variabler som henter sine verdier fra et kodeverk, f.eks. «næring» som henter sine verdier fra Standard for næringsgruppering. En skal ikke legge inn hele URI-en, kun id-en for kodeverket^[Id-en er tallet i kodeverkets URI i Klass, f.eks. har Standard for næringsgruppering id=6  https://www.ssb.no/klass/klassifikasjoner/6].

Kodeverkets URI kan endres etter publisering.


::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på Klass-referanse for variabeldefinisjonen med [Navn](#navn) *Sivilstand*:

> 91

Eksempel på Klass-referanse for variabeldefinisjonen med [Navn](#navn) *Landbakgrunn*:

> 25

:::

### Enhetstyper

🌐 *unit_types*

✅

Angir hvilke(n) enhetstype (r) variabelen sier noe om. De fleste variabler vil kun være knyttet til en enhetstype, men noen, kan være knyttet til flere (f.eks. foretak og bedrift). Enhetstyper velges fra meny.

Gyldige verdier er definert i [denne Klass-kodelisten](https://www.ssb.no/klass/klassifikasjoner/702). Verdiene er også [beskrevet her](https://www.ssb.no/metadata/definisjoner-av-statistiske-enheter). Det er enhetstypens kode som skal inn i Vardef, f.eks. **20** hvis enhetstypen er **person**.

Enhetstyper kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

Variabelen «sivilstand» har enhetstype «person». Det har også kapitalinntekt.
Variabelen «produsentpris for tjenester» har enhetstypene «foretak» og «bedrift».

:::

### Statistikkområder

🌐 *subject_fields*

✅

Angir hvilke(t) statistikkområde(r) variabelen tilhører. En kan velge å oppgi Statistikkområde(r) enten på det overordnede nivå 1, eller på det mer detaljerte nivå 2. F.eks. kan en velge å bruke enten statistikkområdet **Befolkning** på nivå 1, eller spesifisere det ytterligere til **Barn, familier og husholdninger** på nivå 2. Det er statistikkområdets kode som skal inn i Vardef, f.eks. **be** dersom statistikkområdet er **Befolkning** eller **be01** dersom det er **Barn, familier og husholdninger**.

Gyldige verdier er definert i [Kodeliste for statistikkområder i Statistikkbanken](https://www.ssb.no/klass/klassifikasjoner/618) i Klass.

Statistikkområder kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på Klass-referanse for statistikkområde for variabeldefinisjonen med [Navn](#navn) *Sivilstand*, der området er **Befolkning**, som har kode **be** i KlASS:

> "be"

Eksempel på Klass-referanse for statistikkområde for variabeldefinisjonen med [Navn](#navn) *Kapitalinntekter*, der området er **Inntekt og forbruk**, som har kode **if** i Klass:

> "if"

:::


### Inneholder særlige kategorier av personopplysninger

🌐 *contains_special_categories_of_personal_data*

✅

Angir om variabelen inneholder spesielt sensitive personopplysninger. En oversikt over hvilke opplysninger dette er, [finnes hos Datatilsynet](https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/om-behandlingsgrunnlag/spesielt-om-sarlige-kategorier-av-personopplysninger/#:~:text=I%20tillegg%20sier%20personopplysningsloven%20%C2%A7%C2%A7%206%2C%207%20og,eller%20historisk%20forskning%20eller%20for%20statistiske%20form%C3%A5l.%20).

Gyldige verdier er `true` og `false`. `false` er standardverdi.


*Inneholder særlige kategorier av personopplysninger* kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

Eksempel 1: Fagforeningsmedlemskap

> true

:::


### Måletype

🌐 *measurement_type*

ℹ️

Angir hvilken måletype variabelen tilhører, f.eks. om den sier noe om energi, valuta eller masse. Brukes ev. kun for kvantitative variabler. Gyldige verdier er to-siffer kode i [denne Klass-kodelisten](https://www.ssb.no/klass/klassifikasjoner/303/koder).

Måletype kan endres etter publisering.




::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på Klass-referanse for måletype for variabeldefinisjonen med [Navn](#navn) *Total produksjon av elektrisk kraft*, der måletypen er **energi**, som har kode **04** i Klass:

> "04"

:::

### Gyldig f.o.m.

🌐 *valid_from*

✅

Angir datoen variabelens definisjon er gyldig f.o.m. Hvis det skjer en større endring i en definisjon, skal det lages en ny gyldighetsperiode for variabelen, og dette markeres ved at den får en ny gyldig f.o.m. dato.  Datoen må være på formatet **YYYY-MM-DD** iht [ISO 8601 Date and time format](https://www.iso.org/iso-8601-date-and-time-format.html#:~:text=Therefore%2C%20the%20order%20of%20the,27%2018%3A00%3A00.000.).

Alle variabler som migreres fra Vardok, og som ikke har en gyldig f.o.m. dato, vil få satt gyldig f.o.m. dato til **1900-01-01**. Denne kan endres så lenge variabelen er et utkast.

Gyldig f.o.m. dato kan ikke endres etter publisering, bortsett fra i det tilfellet at det lages en ny gyldighetsperiode.


::: {.callout-tip collapse="true"}
## Eksempler

Eksempel 1:

> 2003-01-01

Eksempel 2:

> 1993-01-01

:::

::: {.callout-tip collapse="true"}
## Eksempler2
:::: {.columns}

::: {.column width="70%"}
I would like to have text here

Sentence becomes longer, it should automatically stay in their column
:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="20%"}
and here

More text
:::

::::


:::


### Gyldig t.o.m.

🌐 *valid_until*

ℹ️

Angir datoen variabelens definisjon er gyldig t.o.m. Datoen må være på formatet **YYYY-MM-DD** iht [ISO 8601 Date and time format](https://www.iso.org/iso-8601-date-and-time-format.html#:~:text=Therefore%2C%20the%20order%20of%20the,27%2018%3A00%3A00.000.).

Når en ny variabel opprettes, vil gyldig t.o.m. dato oftest være tom (variabelen er gyldig). Dersom en variabel går ut av bruk, dvs. at nåværende gyldighetsperiode ikke erstattes av en ny gyldighetsperiode, settes denne datoen manuelt. Dersom gyldighetsperioden erstattes av en ny gyldighetsperiode, vil datoen settes automatisk til datoen før gyldig f.o.m.-datoen til den nye gyldighetsperioden.

Gyldig t.o.m. dato kan endres etter publisering dersom variabelen slutter å være gyldig (ingen nye gyldighetsperioder).


::: {.callout-tip collapse="true"}
## Eksempler

Eksempel 1:

> 2003-01-01

Eksempel 2:

> 1993-01-01

:::

### URI til ekstern referanse

🌐 *external_reference_uri*

ℹ️

Angir ekstern definisjon/dokumentasjon, f.eks. en nettside
som er relevant for variabelen.

Ekstern referanse kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

For har eksempel variabelen *Fagforeningskontigent* følgende ekstern referanse:

> https://www.skatteetaten.no/person/skatt/hjelp-til-riktig-skatt/arbeid-trygd-og-pensjon/fagforeningsfradrag/

:::

### Merknad

🌐 *comment*

**nb** | **nn** | **en**

ℹ️

Angir eventuelle tilleggsopplysninger som ikke hører hjemme i selve definisjonen.

Merknad kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

Variabelen **Landbakgrunn** for eksempel følgende merknad:

> "Fra og med 1.1.2003 ble definisjon endret til også å trekke inn besteforeldrenes fødeland."

Variabelen **Skattefrie overføringer** har for eksempel følgende merknad:

> "Alle mottatte overføringer gjelder i løpet av kalenderåret. Engangsstønaden ble innlemmet f.o.m. inntektsåret 1994. Kontantstøtten ble innlemmet fra august 1998. Forsørgerfradraget opphørte f.o.m. inntektsåret 2001.Skattefrie overføringer omfatter også samleposten "andre overføringer", se eksterne kommentarer knyttet til denne variabelen."

:::


### URI til relevante variabeldefinisjoner

🌐 *related_variable_definition_uris*

ℹ️

Angir URIer til andre Vardef-variabeldefinisjoner som er relevante.

Kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

Variabelen **Inntekt etter skatt** kan for eksempel lenke annen relevant variabeldefinisjon, f.eks. **Renteinntekter.

:::


### ID

🌐 *id*

✅

Angir den unike SSB-identifikatoren for variabelen. ID-en maskingenereres i Vardef.

ID kan ikke endres.

::: {.callout-tip collapse="true"}
## Eksempler

Eksempel på en generert ID:

> "5AlkmJ6x"

:::


### Kontakt

🌐 *contact*

**nb** | **nn** | **en**

✅

Angir navn og epost for person eller gruppe som kan svare på spørsmål knyttet til variabeldefinisjonen. Tittel oppgis på bokmål, nynorsk og engelsk.

Kontakt kan endres etter publisering

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan kontaktfeltet se slik ut:

```{.yaml filename="yaml"}
contact:
    title:
        nb: |-
            Bedrifts- og foretaksregisteret
        nn: |-
            Bedrifts- og foretaksregisteret
        en: |-
            The Central Register of Establishments and Enterprises
    email: bof@ssb.no
```

:::

### Sist oppdatert

🌐 *last_updated_at*

✅

Angir dato for siste oppdatering av variabelen (gjelder alle typer endringer). Datoen maskingenereres.

Sist oppdatert – dato kan ikke endres.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan **Sist oppdatert** ha følgende verdi:

> "2025-06-10T12: 30: 13.765000"

:::

### Eier

🌐 *owner*

✅

Angir eier av variabelen dvs. ansvarlig Dapla-team (statistikk-team) og informasjon om tilgangsstyringsgrupper. Team-tilhørighet og gruppe settes automatisk til det samme som team- og gruppetilhørigheten til den som oppretter variabelen.

Eier kan endres etter publisering.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan eierfeltet se slik ut:

```{.yaml filename="yaml"}
owner:
    team: "dapla-felles"
    groups:
        - "dapla-felles-developers"
```

:::

### Variabelens status

🌐 *variable_status*

✅

Angir livssyklus for variabelen. Denne har tre kategorier:

#### **Utkast**

🌐 *DRAFT*

Utkast/kladd, dvs. under konstruksjon - "arbeid pågår" .

#### **Publisert internt**

🌐 *PUBLISHED_INTERNAL*

Godkjent og publisert internt.

#### **Publisert eksternt**

🌐 *PUBLISHED_EXTERNAL*

Godkjent og publisert eksternt.


Statusen «Publisert internt» kan kun endres til «Publisert eksternt». Slik unngår en at interne brukere mister tilgang til variabler som har vært publisert internt.

Statusen «Publisert eksternt» kan ikke endres. Slik unngår en at eksterne brukere mister tilgang til variabler som har vært publisert eksternt.

Det er mulig å kun publisere en variabel internt på bokmål eller nynorsk, og uten engelsk, men for å publisere eksternt, må alle relevante felt være oversatt til bokmål, nynorsk og engelsk (dvs. navn, definisjon, ev. merknad og kontakt/tittel).

### Opprettet av

🌐 *created_by*

✅

Angir epostadressen til personen (initialer) som har opprettet variabelen. Verdien er maskingenerert.

**Opprettet av** kan ikke endres.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan **Opprettet av** ha følgende verdi:

> "ini@ssb.no"

:::

### Opprettet

🌐 *created_at*

✅

Angir datoen variabelen ble opprettet. Maskingenereres ved opprettelsen av ny variabel.

**Opprettet** kan ikke endres.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan **Opprettet** ha følgende verdi:

> "2025-06-10T12: 30: 13.765000"

:::

### Sist oppdatert av

🌐 *last_updated_by*

✅

Angir e-posten til personen (initialer) som sist utførte en endring i variabelen. Maskingenereres av systemet ved alle typer endringer.

**Sist oppdatert av** kan ikke endres.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan **Sist oppdatert av** ha følgende verdi:

> "ini@ssb.no"

:::

### Endrings-ID

🌐 *patch_id*

✅

Angir ID for endringer på en publisert variabel. ID-en settes automatisk av systemet, og viser på et gitt tidspunkt hvor mange ganger variabelen er endret. Ved første lagring av et utkast settes endrings-ID lik 1. Ved endringer på en publisert variabel vil hver endring øke endrings-ID med 1.

Endring- id kan kun endres av systemet.

::: {.callout-tip collapse="true"}
## Eksempler

For eksempel kan **Endrings-ID** ha følgende verdi:

> 2

:::
