# Lenker

Dokumentasjon for utviklere i SSB er spredt over mange ulike sider. Denne siden er en oversikt over dokumentasjonen som finnes.

## Samhandling

- [Slack](https://ssb-norge.slack.com)
- [GitHub](https://github.com/statisticsnorway)
- [Confluence](https://statistics-norway.atlassian.net/wiki/home)
- [Byrånettet](https://ssbno.sharepoint.com/sites/byraanettet)

## Plattform

### SSB Backstage

<https://backstage.intern.ssb.no>

- Programvarekatalog
- Teamkatalog
- Teknologiradar

### Nais

- Offisielle docs fra nav: <https://docs.ssb.cloud.nais.io/>
- Intern system docs: <https://statisticsnorway.github.io/nais-system> (krever GitHub innlogging)
- Nais console: <https://console.ssb.cloud.nais.io/> (krever [naisdevice](https://docs.ssb.cloud.nais.io/operate/naisdevice/how-to/install/))

### Dapla

- Dapla ctrl (teamkatalog): <https://dapla-ctrl.intern.ssb.no/>

### Dapla Lab

- <https://lab.dapla.ssb.no/>
- Intern system docs: <https://statisticsnorway.github.io/dapla-lab-system> (krever GitHub innlogging)
- Brukerdokumentasjon: <https://manual.dapla.ssb.no/statistikkere/dapla-lab.html>

### Utgått

- <https://docs.bip.ssb.no> (krever GitHub innlogging)
- <https://docs.dapla.ssb.no/> (krever GitHub innlogging)

## Arkitektur

- [Arkitekturprinsipper](https://statistics-norway.atlassian.net/wiki/x/AYDs0g)
- [Architecture Decision Records](https://adr.ssb.no) (krever GitHub innlogging)
- [Teknologiradar](https://backstage.intern.ssb.no/tech-radar) (krever [naisdevice](https://docs.ssb.cloud.nais.io/operate/naisdevice/how-to/install/))

## Oppsett

Generellt er utviklere i SSB veldig fri til å velge sin lokal dev-oppsett utifra preferanser og teknologivalg. Følgende lenker går på SSB spesifikk oppsett, særlig relatert til nettverkstilgang og sikkerhet ellers.

- [Kundeservice FAQ](https://ssbno.sharepoint.com/sites/IT-service/SitePages/FAQ.aspx?e=VN49nD&share=Ec6hmugapi9JrCHxcgGnujkB7AVgu7SPNCIypjaoETjGQw)
    - WiFi
    - Microsoft Authenticator
    - VPN
    - Epost
    - Passordbytte
- [Git/GitHub](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3041493000/Hvordan-beskrivelser)
- [IntelliJ lisenser](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/2586050661/Verkt+y)
- [Installer naisdevice](https://docs.ssb.cloud.nais.io/operate/naisdevice/how-to/install/)

## Test og kvalitet

### Tilgjengelige tjenester

- [Dependabot](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3037626783/Sikkerhetstester+i+SSB#Dependabot)
- [Snyk](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3037626783/Sikkerhetstester+i+SSB#Snyk)
- [Detectify](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3037626783/Sikkerhetstester+i+SSB#Detectify)
- [Sonarcloud](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3565748420/SonarCloud+kodekvalitetsverkt+y)
- [Mabl]()

## Prosess

- [Operasjonell modell](https://statistics-norway.atlassian.net/wiki/spaces/A700/pages/3522494510/Operasjonell+modell+Avdeling+for+IT+-+A700)
- [IT Avdelingens leveranse demo](https://statistics-norway.atlassian.net/wiki/spaces/A700/pages/875954203/IT+Avdelingens+leveranse+demo) (finner sted en gang i måneden på fredag)
