---
title: Endringer i editeringsrammeverket og tilhørende artikkel
categories:
    - ssb-dash-framework
    - editering
    - dapla-manual
author:
  - name: Alex Crozier
    affiliation:
      - name: A200 Støtteteam
        email: akc@ssb.no
date: 10/20/2025
date-modified: 10/20/2025
---

Vi har videreutviklet editeringsrammeverket (python-pakken [`ssb-dash-framework`](https://pypi.org/project/ssb-dash-framework/)) og [tilhørende artikkel i manualen](../../../statistikkere/editeringsrammeverk.qmd).

### Editering av dataframes

Rammeverket støtter nå loggføring av endringer på dataframes og dermed editering av dataframes. Kort fortalt lagrer rammeverket en logg i .json-format. Man kan deretter lese inn loggen og påføre endringene på dataframen med funksjonen `apply_edits` som også er i pakken.

:::{.callout-warning}
# Endringene er foreløpig kun tilgjengelig i pre-release

Om man skal få denne funksjonaliteten må man spesifisere `--allow-prerelease` i poetry slik:

`poetry add ssb-dash-framework --allow-prerelease`

evt. `poetry update ssb-dash-framework --allow-prerelease` dersom man har pakken fra før.
:::

## Hva betyr dette for meg?

Det betyr at du nå kan editere dataframes på Dapla uten å bruke EimerDB!
