project:
  type: website
  output-dir: _site
  resources:
    - CNAME # required for custom domain on Publish

website:
  title: 'Dapla-manualen'
  image: images/dapla-long.png
  favicon: images/dapla-favicon.png
  site-url: https://manual.dapla.ssb.no
  description: 'Brukermanualen for SSBs dataplattform Dapla'
  repo-url: https://github.com/statisticsnorway/dapla-manual
  repo-subdir: dapla-manual
  issue-url: https://github.com/statisticsnorway/dapla-manual/issues/new
  repo-actions: [edit, issue, source]
  twitter-card: true
  page-navigation: true
  open-graph: true
  page-footer:
    left: This site is heavily inspired by the
      [Quarto website](https://quarto.org/).
    center: |
      Kom i gang med Dapla

  navbar:
    logo: images/dapla-long.png
    logo-alt: 'Logo for Dapla'
    background: '#F0F8F9' # "Dark 2" from https://design.ssb.no/#/components/color
    foreground: '#274247' # "Dark 5" from https://design.ssb.no/#/components/color
    search: true
    left:
      - text: Manual
        href: statistikkere/index.qmd
      - text: Nyheter
        href: news/index.qmd
      - text: "Blogg"
        href: blog/index.qmd
      - text: FAQ
        href: faq.qmd
      - text: Eksempler
        href: notebooks/index.qmd
      - text: Utviklere
        href: utviklere/lenker.qmd
      - text: 'Om Dapla'
        href: om-dapla.qmd
      - text: Hjelp
        menu:
          - text: Dapla Ctrl
            icon: people-fill
            href: https://dapla-ctrl.intern.ssb.no/
          - text: Diskusjonsforum
            icon: people-fill
            href: https://web.yammer.com/main/org/ssb.no/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5MDUzMjA2In0/all
          - text: Kundeservice
            icon: send-fill
            href: https://ssb.pureservice.com/#/new/7
    right:
      - text: 'Dapla Lab (prod)'
        href: https://lab.dapla.ssb.no/
        icon: graph-up
      - icon: github
        text: Besøk repoet
        href: https://github.com/statisticsnorway/dapla-manual
        aria-label: Dapla-manual GitHub repository
      - text: 'Andre lenker'
        menu:
          - text: 'Dapla Lab (test)'
            href: https://lab.dapla-test.ssb.no/
            icon: graph-up-arrow
          - text: 'Dapla Lab (dev)'
            href: https://lab.dapla-dev.ssb.no/
            icon: graph-up-arrow
          - text: 'Google Cloud Console'
            href: https://console.cloud.google.com/
            icon: google
          - text: 'Dapla Ctrl'
            href: https://dapla-ctrl.intern.ssb.no/
            icon: controller


  sidebar:
    - id: statistikkere
      collapse-level: 1
      contents:
        - section: "Kom i gang"
          href: statistikkere/index.qmd
          contents:
            - statistikkere/index.qmd
            - statistikkere/dapla-overgang.qmd
        - section: "Dapla-team"
          href: statistikkere/hva-er-dapla-team.qmd
          contents:
            - statistikkere/hva-er-dapla-team.qmd
            - statistikkere/tilgangsstyring.qmd
            - statistikkere/administrasjon-av-team.qmd
        - section: "Data"
          href: statistikkere/jobbe-med-data.qmd
          contents:
            - statistikkere/jobbe-med-data.qmd
            - statistikkere/hva-er-botter.qmd
            - statistikkere/deling-av-data.qmd
        - section: "Kode"
          href: statistikkere/git-og-github.qmd
          contents:
            - statistikkere/git-og-github.qmd
            - statistikkere/ssb-project.qmd
            - statistikkere/poetry-ssb-project.qmd
            - statistikkere/renv.qmd
        - section: "Standarder"
          href: "statistikkere/standarder.qmd"
          contents:
            - statistikkere/standarder.qmd
            - statistikkere/datatilstander.qmd
            - statistikkere/navnestandard.qmd
            - statistikkere/kvakk.qmd
        - section: "Dapla Lab"
          href: "statistikkere/dapla-lab.qmd"
          contents:
            - statistikkere/datadoc-editor.qmd
            - statistikkere/jdemetra.qmd
            - statistikkere/jupyter.qmd
            - statistikkere/jupyter-playground.qmd
            - statistikkere/jupyter-pyspark.qmd
            - statistikkere/rstudio.qmd
            - statistikkere/vardef-forvaltning.qmd
            - statistikkere/vscode-python.qmd
        - section: "Metadata"
          href: statistikkere/metadata.qmd
          contents:
            - section: "Datadoc"
              href: statistikkere/datadoc.qmd
              contents:
                - text: "Datamodell"
                  href: statistikkere/datadoc-model.qmd
            - statistikkere/klass.qmd
            - section: "Vardef"
              href: statistikkere/vardef.qmd
              contents:
                - text: "Datamodell"
                  href: statistikkere/vardef-model.qmd
        - section: "Datatjenester"
          href: statistikkere/kildomaten.qmd
          contents:
            - statistikkere/altinn-dapla-suv-tools.qmd
            - statistikkere/kildomaten.qmd
            - statistikkere/dapla-auth-client.qmd
            - statistikkere/dapla-ctrl.qmd
            - statistikkere/dapla-pseudo.qmd
            - section: "dapla-toolbelt-metadata"
              href: statistikkere/dapla-toolbelt-metadata.qmd
              contents:
                - text: "Datadoc"
                  href: statistikkere/datadoc-toolbelt.qmd
                - text: "Vardef"
                  href: statistikkere/vardef-toolbelt.qmd
                - text: "Standards"
                  href: statistikkere/standards-toolbelt.qmd
            - statistikkere/maskinporten-guardian.qmd
            - statistikkere/dapla-statbank-client.qmd
            - statistikkere/data-collector.qmd
            - statistikkere/features.qmd
            - statistikkere/transfer-service.qmd
            - statistikkere/metodebibliotek.qmd
            - statistikkere/gcc.qmd
            - statistikkere/ssb-altinn-python.qmd
        - section: "Altinn 3"
          href: statistikkere/altinn-oversikt.qmd
          contents:
            - text: "Oversikt"
              href: statistikkere/altinn-oversikt.qmd
            - text: "Prefill"
              href: statistikkere/altinn-bygge-prefill.qmd
            - text: "Administrasjon av skjema"
              href: statistikkere/altinn-skjema-administrasjon.qmd
            - text: "SFU"
              href: statistikkere/altinn-sfu.qmd
        - section: "Appendix"
          href: statistikkere/appendix/dashboard.qmd
          contents:
            - statistikkere/appendix/contribution.qmd
            - statistikkere/appendix/arkivering.qmd
            - statistikkere/appendix/dashboard.qmd
            - statistikkere/appendix/innlogging.qmd
            - statistikkere/appendix/jit.qmd
            - statistikkere/appendix/spark.qmd
            - statistikkere/appendix/kartdata.qmd
            - statistikkere/appendix/filinnsamling-moveit.qmd
            - statistikkere/appendix/langtkjorende-jobber.qmd
    - id: utviklere
      collapse-level: 1
      contents:
        - utviklere/lenker.qmd
        - utviklere/dokumentere-for-backstage.qmd
    - id: eksempler
      collapse-level: 1
      contents:
        - notebooks/index.qmd
        - text: 'PySpark - Introduksjon'
          href: ../notebooks/spark/pyspark-intro.html
        - text: 'PySpark - Delta Lake'
          href: ../notebooks/spark/deltalake-intro.html
        - text: 'SparkR - Introduksjon'
          href: ../notebooks/spark/sparkr-intro.html

freeze: true

bibliography: references.bib

format:
  html:
    toc: true
    collapse-level: 1
    theme: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
