project:
  type: website
  output-dir: _site
  resources:
    - CNAME # required for custom domain on Publish

website:
  title: 'Dapla-manualen'
  image: images/dapla-long.png
  favicon: images/dapla-favicon.png
  site-url: https://manual.dapla.ssb.no
  repo-url: https://github.com/statisticsnorway/dapla-manual
  repo-subdir: dapla-manual
  issue-url: https://github.com/statisticsnorway/dapla-manual/issues/new
  repo-actions: [edit, issue, source]
  twitter-card: true
  page-navigation: true
  open-graph: true
  page-footer:
    left: This site is heavily inspired by the
      [Quarto website](https://quarto.org/).
    center: |
      Kom i gang med Dapla

  navbar:
    logo: images/dapla-long.png
    logo-alt: 'Logo for Dapla'
    background: '#F0F8F9' # "Dark 1" from https://design.ssb.no/#/components/color
    foreground: '#274247' # "Dark 5" from https://design.ssb.no/#/components/color
    search: true
    left:
      - text: Manual
        href: statistikkere/index.qmd
      - text: Utviklere
        href: utviklere/lenker.qmd
      - text: Nyheter
        href: news/index.qmd
      - text: "Blogg"
        href: blog/index.qmd
      - text: Eksempler
        href: notebooks/index.qmd
      - text: 'Om Dapla'
        href: om-dapla.qmd
      - text: Hjelp
        menu:
          - text: Dapla Ctrl
            icon: people-fill
            href: https://start.dapla.ssb.no/
          - text: Diskusjonsforum
            icon: people-fill
            href: https://web.yammer.com/main/org/ssb.no/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5MDUzMjA2In0/all
          - text: Kundeservice
            icon: send-fill
            href: https://ssb.pureservice.com/#/new/7
          - text: FAQ
            icon: question-circle-fill
            href: faq.qmd
          - text: FAQ Dapla Lab
            icon: question-circle-fill
            href: faq-dapla-lab.qmd
    right:
      - text: 'Logg inn'
        icon: person-circle
        menu:
          - text: 'Dapla Lab (prod)'
            href: https://lab.dapla.ssb.no/
            icon: graph-up
          - text: 'Dapla Lab (test)'
            href: https://lab.dapla-test.ssb.no/
            icon: graph-up-arrow
          - text: 'Dapla Lab (dev)'
            href: https://lab.dapla-dev.ssb.no/
            icon: graph-up-arrow
          - text: 'JupyterLab (prod)'
            href: https://jupyter.dapla.ssb.no/
            icon: journal-code
          - text: 'JupyterLab (staging)'
            href: https://jupyter.dapla-staging.ssb.no/
            icon: journal-code
          - text: 'Google Cloud Console'
            href: https://console.cloud.google.com/
            icon: google
          - text: 'DaplaHub (POC)'
            href: https://datahub.external.staging.ssb.cloud.nais.io/explore
            icon: database-fill
          - text: 'Dapla Ctrl'
            href: https://ctrl.dapla.ssb.no/
            icon: controller
      - icon: github
        href: https://github.com/statisticsnorway/dapla-manual
        aria-label: Dapla-manual GitHub repository

  sidebar:
    - id: statistikkere
      collapse-level: 1
      contents:
        - href: statistikkere/index.qmd
        - section: "Dapla-team"
          href: statistikkere/hva-er-dapla-team.qmd
          contents:
            - statistikkere/hva-er-dapla-team.qmd
            - statistikkere/tilgangsstyring.qmd
            - statistikkere/administrasjon-av-team.qmd
        - section: "Data"
          href: statistikkere/jobbe-med-data.qmd
          contents:
            - statistikkere/jobbe-med-data.qmd
            - statistikkere/hva-er-botter.qmd
            - statistikkere/deling-av-data.qmd
        - section: "Kode"
          href: statistikkere/git-og-github.qmd
          contents:
            - statistikkere/git-og-github.qmd
            - statistikkere/ssb-project.qmd
            - statistikkere/poetry-ssb-project.qmd
            - statistikkere/renv.qmd
        - section: "Standarder"
          href: "statistikkere/standarder.qmd"
          contents:
            - statistikkere/standarder.qmd
            - statistikkere/datatilstander.qmd
            - statistikkere/navnestandard.qmd
            - statistikkere/kvakk.qmd
        - section: "Dapla Lab"
          href: "statistikkere/dapla-lab.qmd"
          contents:
            - statistikkere/dapla-lab.qmd
            - statistikkere/datadoc.qmd
            - statistikkere/jdemetra.qmd
            - statistikkere/jupyter.qmd
            - statistikkere/jupyter-playground.qmd
            - statistikkere/jupyter-pyspark.qmd
            - statistikkere/rstudio.qmd
            - statistikkere/vscode-python.qmd
        - section: "Metadata"
          href: statistikkere/metadata.qmd
          contents:
            - statistikkere/metadata.qmd
        - section: "Datatjenester"
          href: statistikkere/kildomaten.qmd
          contents:
            - statistikkere/kildomaten.qmd
            - statistikkere/dapla-ctrl.qmd
            - statistikkere/dapla-pseudo.qmd
            - statistikkere/dapla-toolbelt-metadata.qmd
            - statistikkere/maskinporten-guardian.qmd
            - statistikkere/statistikkbanken.qmd
            - statistikkere/data-collector.qmd
            - statistikkere/metadata.qmd
            - statistikkere/features.qmd
            - statistikkere/transfer-service.qmd
            - statistikkere/metodebibliotek.qmd
            - statistikkere/gcc.qmd
        - section: "Appendix"
          href: statistikkere/dashboard.qmd
          contents:
            - statistikkere/contribution.qmd
            - statistikkere/arkivering.qmd
            - statistikkere/dashboard.qmd
            - statistikkere/innlogging.qmd
            - statistikkere/jit.qmd
            - statistikkere/spark.qmd
            - statistikkere/altinn3.qmd
            - statistikkere/kartdata.qmd
    - id: utviklere
      collapse-level: 1
      contents:
        - utviklere/lenker.qmd
        - utviklere/dokumentere-for-backstage.qmd
    - id: eksempler
      collapse-level: 1
      contents:
        - notebooks/index.qmd
        - text: 'PySpark - Introduksjon'
          href: ../notebooks/spark/pyspark-intro.html
        - text: 'PySpark - Delta Lake'
          href: ../notebooks/spark/deltalake-intro.html
        - text: 'SparkR - Introduksjon'
          href: ../notebooks/spark/sparkr-intro.html

freeze: true

bibliography: references.bib

format:
  html:
    toc: true
    collapse-level: 1
    theme: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
