project:
  type: website
  output-dir: _site
  resources:
    - CNAME # required for custom domain on Publish

website:
  title: 'Dapla-manualen'
  image: images/dapla-long.png
  favicon: images/dapla-favicon.png
  repo-url: https://github.com/statisticsnorway/dapla-manual-internal
  issue-url: https://github.com/statisticsnorway/dapla-manual-internal/issues/new
  repo-actions: [edit, issue]
  twitter-card: true
  page-navigation: true
  open-graph: true
  page-footer:
    left: This site is heavily inspired by the
      [Quarto website](https://quarto.org/).
    center: |
      Kom i gang med Dapla

  navbar:
    logo: images/dapla-long.png
    logo-alt: 'Logo for Dapla'
    background: '#F0F8F9' # "Dark 1" from https://design.ssb.no/#/components/color
    foreground: '#274247' # "Dark 5" from https://design.ssb.no/#/components/color
    search: true
    left:
      - text: Statistikkere
        href: statistikkere/index.qmd
      - text: Utviklere
        href: utviklere/index.qmd
      - text: Eksempler
        href: notebooks/index.qmd
      - text: 'Om Dapla'
        href: om-dapla.qmd
      - text: Hjelp
        menu:
          - text: Opprette Dapla-team
            icon: people-fill
            href: https://start.dapla.ssb.no/
          - text: Diskusjonsforum
            icon: people-fill
            href: https://web.yammer.com/main/org/ssb.no/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5MDUzMjA2In0/all
          - text: Kundeservice
            icon: send-fill
            href: https://ssb.pureservice.com/#/new/7
          - text: FAQ
            icon: question-circle-fill
            href: faq.qmd
    right:
      - text: 'Logg inn'
        icon: person-circle
        menu:
          - text: 'DaplaHub'
            href: https://datahub.external.staging.ssb.cloud.nais.io/explore
            icon: database-fill
          - text: 'DaplaLab'
            href: om-dapla.qmd
            icon: graph-up
          - text: 'JupyterLab (legacy)'
            href: hhttps://jupyter.dapla.ssb.no/
            icon: journal-code
          - text: 'Google Cloud Console'
            href: https://console.cloud.google.com/
            icon: google
      - icon: github
        href: https://github.com/statisticsnorway/dapla-manual-internal
        aria-label: Dapla-manual GitHub repository

  sidebar:
    - id: statistikkere
      collapse-level: 1
      contents:
        - href: statistikkere/index.qmd
        - href: statistikkere/hurtigstart.qmd
        - section: "Dapla-team"
          href: statistikkere/hva-er-dapla-team.ipynb
          contents:
            - statistikkere/hva-er-dapla-team.ipynb
            - statistikkere/tilgangsstyring.ipynb
            - statistikkere/administrasjon-av-team.qmd
            - statistikkere/features.qmd
        - section: "Data"
          href: statistikkere/jobbe-med-data.qmd
          contents:
            - statistikkere/jobbe-med-data.qmd
            - statistikkere/hva-er-botter.qmd
        - section: "Programmering"
          href: statistikkere/jobbe-med-kode.qmd
          contents:
            - statistikkere/jobbe-med-kode.qmd
            - statistikkere/git-og-github.qmd
        - section: "Standarder"
          href: "statistikkere/datatilstander.qmd"
          contents:
            - statistikkere/datatilstander.qmd
            - statistikkere/navnestandard-datalagring.qmd
            - statistikkere/versjonering-av-datasett.qmd
        - section: "Metadata"
          href: statistikkere/datadoc.qmd
          contents:
            - statistikkere/datadoc.qmd
        - section: statistikkere/daplalab-overview.qmd
          contents:
            - statistikkere/jupyterlab.qmd
        - section: "Datatjenester"
          href: statistikkere/kildomaten.qmd
          contents:
            - statistikkere/gcc.qmd
            - statistikkere/kildomaten.qmd
            - statistikkere/transfer-service.ipynb
            - statistikkere/statistikkbanken.qmd
        - section: "Appendix"
          href: statistikkere/dashboard.qmd
          contents:
            - statistikkere/dashboard.qmd
            - statistikkere/innlogging.qmd
            - statistikkere/spark.qmd
            - statistikkere/altinn3.qmd
            - statistikkere/kartdata.qmd
    - id: utviklere
      collapse-level: 1
      contents:
        - href: utviklere/forord.qmd
        - section: utviklere/index.qmd
          contents:
            - utviklere/index.qmd
        - section: utviklere/tldr/tldr.qmd
          contents:
            - utviklere/tldr/kultur.qmd
            - utviklere/tldr/utvikling.qmd
            - utviklere/tldr/versjonskontroll.qmd
            - utviklere/tldr/kvalitet.qmd
            - utviklere/tldr/ci-cd.qmd
            - utviklere/tldr/kjoeremiljoe.qmd
            - utviklere/tldr/infrastruktur.qmd
            - utviklere/tldr/overvaakning.qmd
            - utviklere/tldr/dokumentasjon.qmd
        - section: utviklere/appendix.qmd
          contents:
            - utviklere/iac.qmd
    - id: eksempler
      collapse-level: 1
      contents:
        - notebooks/index.qmd
        - text: 'PySpark - Introduksjon'
          href: ../notebooks/spark/pyspark-intro.html
        - text: 'PySpark - Delta Lake'
          href: ../notebooks/spark/deltalake-intro.html
        - text: 'SparkR - Introduksjon'
          href: ../notebooks/spark/sparkr-intro.html

freeze: true

bibliography: references.bib

format:
  html:
    toc: true
    collapse-level: 1
    theme: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
