project:
  type: website
  output-dir: _site
  resources:
    - CNAME # required for custom domain on Publish

website:
  title: "Dapla-manualen"
  image: images/dapla-long.png
  favicon: images/dapla-favicon.png
  repo-url: https://github.com/statisticsnorway/dapla-manual
  repo-actions: [edit, issue]
  open-graph: true
  search:
    location: sidebar
  page-footer:
    left:
      This is site heavily inspired by the
      [Quarto website](https://quarto.org/).      
    center: |
      Kom i gang med Dapla
  
  navbar:
    logo: images/dapla-long.png
    background: "#F0F8F9" # "Dark 1" from https://design.ssb.no/#/components/color
    foreground: "#274247" # "Dark 5" from https://design.ssb.no/#/components/color
    left:
      - text: Statistikkere
        href: statistikkere/introduksjon.qmd
      - text: Utviklere
        href: utviklere/index.qmd
      - text: Eksempler
        href: notebooks/index.qmd
      - text: Hjelp
        menu:
          - text: Opprette Dapla-team
            icon: people-fill
            href: https://start.dapla.ssb.no/
          - text: Diskusjonsforum
            icon: people-fill
            href: https://web.yammer.com/main/org/ssb.no/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5MDUzMjA2In0/all
          - text: Kundeservice
            icon: send-fill
            href: https://ssb.pureservice.com/#/new/7
    right:
      - icon: github
        href: https://github.com/statisticsnorway/dapla-manual
        aria-label: Dapla-manual GitHub

  sidebar:
    - id: statistikkere
      collapse-level: 1
      contents:
        - href: statistikkere/preface.qmd
        - section: hurtigstart/index.qmd
          contents:
            - hurtigstart/hva-er-dapla.qmd
            - statistikkere/innlogging.qmd
        - section: statistikkere/introduksjon.qmd
          contents:
            - statistikkere/hva-er-dapla.qmd
            - statistikkere/innlogging.qmd
        - section: statistikkere/statistikkproduksjon.qmd
          contents:
          - section: statistikkere/dapla-team.qmd
            contents:
            - statistikkere/hva-er-dapla-team.qmd
            - statistikkere/administrasjon-av-team.qmd
          - statistikkere/gcc.qmd
          - statistikkere/overføring-av-data.qmd
          - section: statistikkere/produksjonsløp.qmd
            contents:
            - statistikkere/jobbe-med-kode.qmd
            - section: statistikkere/jobbe-med-data.qmd
              contents:
              - statistikkere/hva-er-botter.qmd
            - section: statistikkere/standarder.qmd
              contents:
                - statistikkere/datatilstander.qmd
                - statistikkere/navnestandard-datalagring.qmd
                - statistikkere/versjonering-av-datasett.qmd
            - section: statistikkere/kildedata.qmd
              contents:
              - statistikkere/automatisering.qmd
              - statistikkere/automatisering-avansert.qmd
            - statistikkere/statistikkbanken.qmd
        - section: statistikkere/visualisering.qmd
          contents:
          - statistikkere/dashboard.qmd
        - section: statistikkere/annet.qmd
          contents:
          - statistikkere/git-og-github.qmd
          - statistikkere/datadoc.qmd
          - statistikkere/github-app-integrasjon.qmd
          - statistikkere/gjenopprette-data.qmd
          - statistikkere/spark.qmd
          - statistikkere/slette-data.qmd
          - statistikkere/altinn3.qmd
          - statistikkere/kartdata.qmd
        - statistikkere/ordforklaringer.qmd
        - statistikkere/contribution.qmd
    - id: utviklere
      collapse-level: 1
      contents:
        - href: utviklere/forord.qmd
        - section: utviklere/index.qmd
          contents:
            - utviklere/index.qmd
        - section: utviklere/appendix.qmd
          contents:
            - utviklere/iac.qmd
    - id: eksempler
      collapse-level: 1
      contents:
        - notebooks/index.qmd
        - text: "PySpark - Introduksjon"
          href: ../notebooks/spark/pyspark-intro.html
        - text: "PySpark - Delta Lake"
          href: ../notebooks/spark/deltalake-intro.html
        - text: "SparkR - Introduksjon"
          href: ../notebooks/spark/sparkr-intro.html

freeze: true

bibliography: references.bib

format:
  html:
    toc: true
    collapse-level: 1
    theme: cosmo
    code-copy: true
    code-overflow: wrap
