name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    concurrency:
      group: gh-pages-updates
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0
      - uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0
        if: github.event.action != 'closed'
        with:
          to: html
          path: dapla-manual
      - name: Check if PR is still open
        id: check_pr
        run: |
          STATE=$(gh pr view ${{ github.event.pull_request.number }} --json state --jq .state)
          echo "state=$STATE" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy PR Preview
        if: steps.check_pr.outputs.state == 'OPEN'
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1.8.1
        with:
          source-dir: ./dapla-manual/_site # The folder where Quarto renders the site
          token: ${{ secrets.GITHUB_TOKEN }}
